// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ambilin.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseRequest struct {
	TxType               string            `protobuf:"bytes,1,opt,name=txType,proto3" json:"txType,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params               []byte            `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	BodyString           map[string]string `protobuf:"bytes,4,rep,name=bodyString,proto3" json:"bodyString,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{0}
}

func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (m *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(m, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *BaseRequest) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *BaseRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *BaseRequest) GetBodyString() map[string]string {
	if m != nil {
		return m.BodyString
	}
	return nil
}

type BaseResponse struct {
	Response             []byte            `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	HttpStatus           int32             `protobuf:"varint,3,opt,name=httpStatus,proto3" json:"httpStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{1}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *BaseResponse) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *BaseResponse) GetHttpStatus() int32 {
	if m != nil {
		return m.HttpStatus
	}
	return 0
}

type MessageProto struct {
	Text                 []byte   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageProto) Reset()         { *m = MessageProto{} }
func (m *MessageProto) String() string { return proto.CompactTextString(m) }
func (*MessageProto) ProtoMessage()    {}
func (*MessageProto) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{2}
}

func (m *MessageProto) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageProto.Unmarshal(m, b)
}
func (m *MessageProto) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageProto.Marshal(b, m, deterministic)
}
func (m *MessageProto) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageProto.Merge(m, src)
}
func (m *MessageProto) XXX_Size() int {
	return xxx_messageInfo_MessageProto.Size(m)
}
func (m *MessageProto) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageProto.DiscardUnknown(m)
}

var xxx_messageInfo_MessageProto proto.InternalMessageInfo

func (m *MessageProto) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

type SessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	RequestId            string   `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{3}
}

func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(m, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SessionRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *SessionRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type SessionResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *SessionData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	RequestId            string       `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{4}
}

func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (m *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(m, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

func (m *SessionResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SessionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SessionResponse) GetData() *SessionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SessionResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type SessionData struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionData) Reset()         { *m = SessionData{} }
func (m *SessionData) String() string { return proto.CompactTextString(m) }
func (*SessionData) ProtoMessage()    {}
func (*SessionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{5}
}

func (m *SessionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionData.Unmarshal(m, b)
}
func (m *SessionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionData.Marshal(b, m, deterministic)
}
func (m *SessionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionData.Merge(m, src)
}
func (m *SessionData) XXX_Size() int {
	return xxx_messageInfo_SessionData.Size(m)
}
func (m *SessionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionData.DiscardUnknown(m)
}

var xxx_messageInfo_SessionData proto.InternalMessageInfo

func (m *SessionData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SessionData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SessionData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SessionData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SessionData) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type UserRequest struct {
	RequestId            string    `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string    `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	User                 *DataUser `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{6}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *UserRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *UserRequest) GetUser() *DataUser {
	if m != nil {
		return m.User
	}
	return nil
}

type UserResponse struct {
	Status               int32       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string      `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string      `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string      `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	DataUser             *DataUser   `protobuf:"bytes,5,opt,name=dataUser,proto3" json:"dataUser,omitempty"`
	ListUser             []*DataUser `protobuf:"bytes,6,rep,name=listUser,proto3" json:"listUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{7}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *UserResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *UserResponse) GetDataUser() *DataUser {
	if m != nil {
		return m.DataUser
	}
	return nil
}

func (m *UserResponse) GetListUser() []*DataUser {
	if m != nil {
		return m.ListUser
	}
	return nil
}

type DataUser struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed              int64    `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,5,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	Ektp                 string   `protobuf:"bytes,11,opt,name=ektp,proto3" json:"ektp,omitempty"`
	AccountNumber        string   `protobuf:"bytes,12,opt,name=accountNumber,proto3" json:"accountNumber,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,13,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	Status               int32    `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	RegistrationCode     int32    `protobuf:"varint,15,opt,name=registrationCode,proto3" json:"registrationCode,omitempty"`
	AccessId             string   `protobuf:"bytes,16,opt,name=accessId,proto3" json:"accessId,omitempty"`
	AgentId              string   `protobuf:"bytes,17,opt,name=agentId,proto3" json:"agentId,omitempty"`
	ClientPin            string   `protobuf:"bytes,18,opt,name=clientPin,proto3" json:"clientPin,omitempty"`
	FirstLogin           bool     `protobuf:"varint,19,opt,name=firstLogin,proto3" json:"firstLogin,omitempty"`
	UserType             string   `protobuf:"bytes,20,opt,name=userType,proto3" json:"userType,omitempty"`
	GuarantorName        string   `protobuf:"bytes,21,opt,name=guarantorName,proto3" json:"guarantorName,omitempty"`
	IdentityNumber       string   `protobuf:"bytes,22,opt,name=identityNumber,proto3" json:"identityNumber,omitempty"`
	FeePickup            string   `protobuf:"bytes,23,opt,name=feePickup,proto3" json:"feePickup,omitempty"`
	KanwilId             int32    `protobuf:"varint,24,opt,name=kanwilId,proto3" json:"kanwilId,omitempty"`
	KancaId              int32    `protobuf:"varint,25,opt,name=kancaId,proto3" json:"kancaId,omitempty"`
	PartnerId            string   `protobuf:"bytes,26,opt,name=partnerId,proto3" json:"partnerId,omitempty"`
	KanwilName           string   `protobuf:"bytes,27,opt,name=kanwilName,proto3" json:"kanwilName,omitempty"`
	KancaName            string   `protobuf:"bytes,28,opt,name=kancaName,proto3" json:"kancaName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataUser) Reset()         { *m = DataUser{} }
func (m *DataUser) String() string { return proto.CompactTextString(m) }
func (*DataUser) ProtoMessage()    {}
func (*DataUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{8}
}

func (m *DataUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataUser.Unmarshal(m, b)
}
func (m *DataUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataUser.Marshal(b, m, deterministic)
}
func (m *DataUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataUser.Merge(m, src)
}
func (m *DataUser) XXX_Size() int {
	return xxx_messageInfo_DataUser.Size(m)
}
func (m *DataUser) XXX_DiscardUnknown() {
	xxx_messageInfo_DataUser.DiscardUnknown(m)
}

var xxx_messageInfo_DataUser proto.InternalMessageInfo

func (m *DataUser) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DataUser) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *DataUser) GetRemoved() int64 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *DataUser) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataUser) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *DataUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataUser) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DataUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DataUser) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DataUser) GetEktp() string {
	if m != nil {
		return m.Ektp
	}
	return ""
}

func (m *DataUser) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *DataUser) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *DataUser) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DataUser) GetRegistrationCode() int32 {
	if m != nil {
		return m.RegistrationCode
	}
	return 0
}

func (m *DataUser) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *DataUser) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *DataUser) GetClientPin() string {
	if m != nil {
		return m.ClientPin
	}
	return ""
}

func (m *DataUser) GetFirstLogin() bool {
	if m != nil {
		return m.FirstLogin
	}
	return false
}

func (m *DataUser) GetUserType() string {
	if m != nil {
		return m.UserType
	}
	return ""
}

func (m *DataUser) GetGuarantorName() string {
	if m != nil {
		return m.GuarantorName
	}
	return ""
}

func (m *DataUser) GetIdentityNumber() string {
	if m != nil {
		return m.IdentityNumber
	}
	return ""
}

func (m *DataUser) GetFeePickup() string {
	if m != nil {
		return m.FeePickup
	}
	return ""
}

func (m *DataUser) GetKanwilId() int32 {
	if m != nil {
		return m.KanwilId
	}
	return 0
}

func (m *DataUser) GetKancaId() int32 {
	if m != nil {
		return m.KancaId
	}
	return 0
}

func (m *DataUser) GetPartnerId() string {
	if m != nil {
		return m.PartnerId
	}
	return ""
}

func (m *DataUser) GetKanwilName() string {
	if m != nil {
		return m.KanwilName
	}
	return ""
}

func (m *DataUser) GetKancaName() string {
	if m != nil {
		return m.KancaName
	}
	return ""
}

type OrderSummary struct {
	CreatedDate             string   `protobuf:"bytes,1,opt,name=createdDate,proto3" json:"createdDate,omitempty"`
	StartDate               string   `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate                 string   `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	DepositAmount           float32  `protobuf:"fixed32,4,opt,name=depositAmount,proto3" json:"depositAmount,omitempty"`
	ShippingFee             float32  `protobuf:"fixed32,5,opt,name=shippingFee,proto3" json:"shippingFee,omitempty"`
	InsuranceFee            float32  `protobuf:"fixed32,6,opt,name=insuranceFee,proto3" json:"insuranceFee,omitempty"`
	AgentId                 string   `protobuf:"bytes,7,opt,name=agentId,proto3" json:"agentId,omitempty"`
	TotalTransaction        float32  `protobuf:"fixed32,8,opt,name=totalTransaction,proto3" json:"totalTransaction,omitempty"`
	TotalTransactionSuccess float32  `protobuf:"fixed32,9,opt,name=totalTransactionSuccess,proto3" json:"totalTransactionSuccess,omitempty"`
	TotalTransactionFailed  float32  `protobuf:"fixed32,10,opt,name=totalTransactionFailed,proto3" json:"totalTransactionFailed,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *OrderSummary) Reset()         { *m = OrderSummary{} }
func (m *OrderSummary) String() string { return proto.CompactTextString(m) }
func (*OrderSummary) ProtoMessage()    {}
func (*OrderSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{9}
}

func (m *OrderSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSummary.Unmarshal(m, b)
}
func (m *OrderSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSummary.Marshal(b, m, deterministic)
}
func (m *OrderSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSummary.Merge(m, src)
}
func (m *OrderSummary) XXX_Size() int {
	return xxx_messageInfo_OrderSummary.Size(m)
}
func (m *OrderSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSummary.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSummary proto.InternalMessageInfo

func (m *OrderSummary) GetCreatedDate() string {
	if m != nil {
		return m.CreatedDate
	}
	return ""
}

func (m *OrderSummary) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *OrderSummary) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *OrderSummary) GetDepositAmount() float32 {
	if m != nil {
		return m.DepositAmount
	}
	return 0
}

func (m *OrderSummary) GetShippingFee() float32 {
	if m != nil {
		return m.ShippingFee
	}
	return 0
}

func (m *OrderSummary) GetInsuranceFee() float32 {
	if m != nil {
		return m.InsuranceFee
	}
	return 0
}

func (m *OrderSummary) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *OrderSummary) GetTotalTransaction() float32 {
	if m != nil {
		return m.TotalTransaction
	}
	return 0
}

func (m *OrderSummary) GetTotalTransactionSuccess() float32 {
	if m != nil {
		return m.TotalTransactionSuccess
	}
	return 0
}

func (m *OrderSummary) GetTotalTransactionFailed() float32 {
	if m != nil {
		return m.TotalTransactionFailed
	}
	return 0
}

type OrderSummaryRequest struct {
	RequestId            string        `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string        `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	Params               *OrderSummary `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderSummaryRequest) Reset()         { *m = OrderSummaryRequest{} }
func (m *OrderSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*OrderSummaryRequest) ProtoMessage()    {}
func (*OrderSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{10}
}

func (m *OrderSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSummaryRequest.Unmarshal(m, b)
}
func (m *OrderSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSummaryRequest.Marshal(b, m, deterministic)
}
func (m *OrderSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSummaryRequest.Merge(m, src)
}
func (m *OrderSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_OrderSummaryRequest.Size(m)
}
func (m *OrderSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSummaryRequest proto.InternalMessageInfo

func (m *OrderSummaryRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *OrderSummaryRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *OrderSummaryRequest) GetParams() *OrderSummary {
	if m != nil {
		return m.Params
	}
	return nil
}

type OrderSummaryResponse struct {
	Status               int32         `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string        `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string        `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	Data                 *OrderSummary `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *OrderSummaryResponse) Reset()         { *m = OrderSummaryResponse{} }
func (m *OrderSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*OrderSummaryResponse) ProtoMessage()    {}
func (*OrderSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{11}
}

func (m *OrderSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSummaryResponse.Unmarshal(m, b)
}
func (m *OrderSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSummaryResponse.Marshal(b, m, deterministic)
}
func (m *OrderSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSummaryResponse.Merge(m, src)
}
func (m *OrderSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_OrderSummaryResponse.Size(m)
}
func (m *OrderSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSummaryResponse proto.InternalMessageInfo

func (m *OrderSummaryResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderSummaryResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderSummaryResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *OrderSummaryResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *OrderSummaryResponse) GetData() *OrderSummary {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderRequest struct {
	RequestId            string    `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string    `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	User                 *DataUser `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{12}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *OrderRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *OrderRequest) GetUser() *DataUser {
	if m != nil {
		return m.User
	}
	return nil
}

type OrderResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string       `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string       `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	DataOrder            *DataOrder   `protobuf:"bytes,5,opt,name=dataOrder,proto3" json:"dataOrder,omitempty"`
	ListOrder            []*DataOrder `protobuf:"bytes,6,rep,name=listOrder,proto3" json:"listOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{13}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *OrderResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *OrderResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *OrderResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *OrderResponse) GetDataOrder() *DataOrder {
	if m != nil {
		return m.DataOrder
	}
	return nil
}

func (m *OrderResponse) GetListOrder() []*DataOrder {
	if m != nil {
		return m.ListOrder
	}
	return nil
}

type DataOrder struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed              int64    `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,5,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,7,opt,name=userId,proto3" json:"userId,omitempty"`
	AgentId              string   `protobuf:"bytes,8,opt,name=agentId,proto3" json:"agentId,omitempty"`
	DepositAmount        float32  `protobuf:"fixed32,9,opt,name=depositAmount,proto3" json:"depositAmount,omitempty"`
	ShippingFee          float32  `protobuf:"fixed32,10,opt,name=shippingFee,proto3" json:"shippingFee,omitempty"`
	ShippingMethod       int32    `protobuf:"varint,11,opt,name=shippingMethod,proto3" json:"shippingMethod,omitempty"`
	OrderStatusCustomer  int32    `protobuf:"varint,12,opt,name=orderStatusCustomer,proto3" json:"orderStatusCustomer,omitempty"`
	OrderType            string   `protobuf:"bytes,13,opt,name=orderType,proto3" json:"orderType,omitempty"`
	ProgressPickup       int32    `protobuf:"varint,14,opt,name=progressPickup,proto3" json:"progressPickup,omitempty"`
	OrderLater           string   `protobuf:"bytes,15,opt,name=orderLater,proto3" json:"orderLater,omitempty"`
	EstimatedArrival     string   `protobuf:"bytes,16,opt,name=estimatedArrival,proto3" json:"estimatedArrival,omitempty"`
	EstimatedPickup      string   `protobuf:"bytes,17,opt,name=estimatedPickup,proto3" json:"estimatedPickup,omitempty"`
	CustomerPlace        string   `protobuf:"bytes,18,opt,name=customerPlace,proto3" json:"customerPlace,omitempty"`
	CustomerAddress      string   `protobuf:"bytes,19,opt,name=customerAddress,proto3" json:"customerAddress,omitempty"`
	CustomerLatitude     float32  `protobuf:"fixed32,20,opt,name=customerLatitude,proto3" json:"customerLatitude,omitempty"`
	CustomerLongitude    float32  `protobuf:"fixed32,21,opt,name=customerLongitude,proto3" json:"customerLongitude,omitempty"`
	AgentLatitude        float32  `protobuf:"fixed32,22,opt,name=agentLatitude,proto3" json:"agentLatitude,omitempty"`
	AgentLongitude       float32  `protobuf:"fixed32,23,opt,name=agentLongitude,proto3" json:"agentLongitude,omitempty"`
	OrderStatusAgent     int32    `protobuf:"varint,24,opt,name=orderStatusAgent,proto3" json:"orderStatusAgent,omitempty"`
	CostOrder            float32  `protobuf:"fixed32,25,opt,name=costOrder,proto3" json:"costOrder,omitempty"`
	AmountStatus         bool     `protobuf:"varint,26,opt,name=amountStatus,proto3" json:"amountStatus,omitempty"`
	ExpiredTime          int64    `protobuf:"varint,27,opt,name=expiredTime,proto3" json:"expiredTime,omitempty"`
	CompletedTime        int64    `protobuf:"varint,28,opt,name=completedTime,proto3" json:"completedTime,omitempty"`
	Distance             float32  `protobuf:"fixed32,29,opt,name=distance,proto3" json:"distance,omitempty"`
	ConfirmButton        bool     `protobuf:"varint,30,opt,name=confirmButton,proto3" json:"confirmButton,omitempty"`
	ConfirmButtonAgent   bool     `protobuf:"varint,31,opt,name=confirmButtonAgent,proto3" json:"confirmButtonAgent,omitempty"`
	AmountStatusInvalid  bool     `protobuf:"varint,32,opt,name=amountStatusInvalid,proto3" json:"amountStatusInvalid,omitempty"`
	OrderCode            string   `protobuf:"bytes,33,opt,name=orderCode,proto3" json:"orderCode,omitempty"`
	IsCountdown          bool     `protobuf:"varint,34,opt,name=isCountdown,proto3" json:"isCountdown,omitempty"`
	LocationDescription  string   `protobuf:"bytes,35,opt,name=locationDescription,proto3" json:"locationDescription,omitempty"`
	OrderFinish          int64    `protobuf:"varint,36,opt,name=orderFinish,proto3" json:"orderFinish,omitempty"`
	ExpiredTimeExtend    string   `protobuf:"bytes,37,opt,name=expiredTimeExtend,proto3" json:"expiredTimeExtend,omitempty"`
	UrlInvoice           string   `protobuf:"bytes,38,opt,name=urlInvoice,proto3" json:"urlInvoice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataOrder) Reset()         { *m = DataOrder{} }
func (m *DataOrder) String() string { return proto.CompactTextString(m) }
func (*DataOrder) ProtoMessage()    {}
func (*DataOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{14}
}

func (m *DataOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataOrder.Unmarshal(m, b)
}
func (m *DataOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataOrder.Marshal(b, m, deterministic)
}
func (m *DataOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataOrder.Merge(m, src)
}
func (m *DataOrder) XXX_Size() int {
	return xxx_messageInfo_DataOrder.Size(m)
}
func (m *DataOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DataOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DataOrder proto.InternalMessageInfo

func (m *DataOrder) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DataOrder) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *DataOrder) GetRemoved() int64 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *DataOrder) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataOrder) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *DataOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataOrder) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DataOrder) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *DataOrder) GetDepositAmount() float32 {
	if m != nil {
		return m.DepositAmount
	}
	return 0
}

func (m *DataOrder) GetShippingFee() float32 {
	if m != nil {
		return m.ShippingFee
	}
	return 0
}

func (m *DataOrder) GetShippingMethod() int32 {
	if m != nil {
		return m.ShippingMethod
	}
	return 0
}

func (m *DataOrder) GetOrderStatusCustomer() int32 {
	if m != nil {
		return m.OrderStatusCustomer
	}
	return 0
}

func (m *DataOrder) GetOrderType() string {
	if m != nil {
		return m.OrderType
	}
	return ""
}

func (m *DataOrder) GetProgressPickup() int32 {
	if m != nil {
		return m.ProgressPickup
	}
	return 0
}

func (m *DataOrder) GetOrderLater() string {
	if m != nil {
		return m.OrderLater
	}
	return ""
}

func (m *DataOrder) GetEstimatedArrival() string {
	if m != nil {
		return m.EstimatedArrival
	}
	return ""
}

func (m *DataOrder) GetEstimatedPickup() string {
	if m != nil {
		return m.EstimatedPickup
	}
	return ""
}

func (m *DataOrder) GetCustomerPlace() string {
	if m != nil {
		return m.CustomerPlace
	}
	return ""
}

func (m *DataOrder) GetCustomerAddress() string {
	if m != nil {
		return m.CustomerAddress
	}
	return ""
}

func (m *DataOrder) GetCustomerLatitude() float32 {
	if m != nil {
		return m.CustomerLatitude
	}
	return 0
}

func (m *DataOrder) GetCustomerLongitude() float32 {
	if m != nil {
		return m.CustomerLongitude
	}
	return 0
}

func (m *DataOrder) GetAgentLatitude() float32 {
	if m != nil {
		return m.AgentLatitude
	}
	return 0
}

func (m *DataOrder) GetAgentLongitude() float32 {
	if m != nil {
		return m.AgentLongitude
	}
	return 0
}

func (m *DataOrder) GetOrderStatusAgent() int32 {
	if m != nil {
		return m.OrderStatusAgent
	}
	return 0
}

func (m *DataOrder) GetCostOrder() float32 {
	if m != nil {
		return m.CostOrder
	}
	return 0
}

func (m *DataOrder) GetAmountStatus() bool {
	if m != nil {
		return m.AmountStatus
	}
	return false
}

func (m *DataOrder) GetExpiredTime() int64 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *DataOrder) GetCompletedTime() int64 {
	if m != nil {
		return m.CompletedTime
	}
	return 0
}

func (m *DataOrder) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *DataOrder) GetConfirmButton() bool {
	if m != nil {
		return m.ConfirmButton
	}
	return false
}

func (m *DataOrder) GetConfirmButtonAgent() bool {
	if m != nil {
		return m.ConfirmButtonAgent
	}
	return false
}

func (m *DataOrder) GetAmountStatusInvalid() bool {
	if m != nil {
		return m.AmountStatusInvalid
	}
	return false
}

func (m *DataOrder) GetOrderCode() string {
	if m != nil {
		return m.OrderCode
	}
	return ""
}

func (m *DataOrder) GetIsCountdown() bool {
	if m != nil {
		return m.IsCountdown
	}
	return false
}

func (m *DataOrder) GetLocationDescription() string {
	if m != nil {
		return m.LocationDescription
	}
	return ""
}

func (m *DataOrder) GetOrderFinish() int64 {
	if m != nil {
		return m.OrderFinish
	}
	return 0
}

func (m *DataOrder) GetExpiredTimeExtend() string {
	if m != nil {
		return m.ExpiredTimeExtend
	}
	return ""
}

func (m *DataOrder) GetUrlInvoice() string {
	if m != nil {
		return m.UrlInvoice
	}
	return ""
}

type AgentRating struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	AgentId              string   `protobuf:"bytes,2,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	KetepatanWaktu       bool     `protobuf:"varint,4,opt,name=ketepatanWaktu,proto3" json:"ketepatanWaktu,omitempty"`
	Kesopanan            bool     `protobuf:"varint,5,opt,name=kesopanan,proto3" json:"kesopanan,omitempty"`
	Ketelitian           bool     `protobuf:"varint,6,opt,name=ketelitian,proto3" json:"ketelitian,omitempty"`
	Kerapihan            bool     `protobuf:"varint,7,opt,name=kerapihan,proto3" json:"kerapihan,omitempty"`
	Keterangan           string   `protobuf:"bytes,8,opt,name=keterangan,proto3" json:"keterangan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentRating) Reset()         { *m = AgentRating{} }
func (m *AgentRating) String() string { return proto.CompactTextString(m) }
func (*AgentRating) ProtoMessage()    {}
func (*AgentRating) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{15}
}

func (m *AgentRating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRating.Unmarshal(m, b)
}
func (m *AgentRating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRating.Marshal(b, m, deterministic)
}
func (m *AgentRating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRating.Merge(m, src)
}
func (m *AgentRating) XXX_Size() int {
	return xxx_messageInfo_AgentRating.Size(m)
}
func (m *AgentRating) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRating.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRating proto.InternalMessageInfo

func (m *AgentRating) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *AgentRating) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *AgentRating) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *AgentRating) GetKetepatanWaktu() bool {
	if m != nil {
		return m.KetepatanWaktu
	}
	return false
}

func (m *AgentRating) GetKesopanan() bool {
	if m != nil {
		return m.Kesopanan
	}
	return false
}

func (m *AgentRating) GetKetelitian() bool {
	if m != nil {
		return m.Ketelitian
	}
	return false
}

func (m *AgentRating) GetKerapihan() bool {
	if m != nil {
		return m.Kerapihan
	}
	return false
}

func (m *AgentRating) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type UserRating struct {
	OrderId              string   `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Rating               int32    `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRating) Reset()         { *m = UserRating{} }
func (m *UserRating) String() string { return proto.CompactTextString(m) }
func (*UserRating) ProtoMessage()    {}
func (*UserRating) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{16}
}

func (m *UserRating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRating.Unmarshal(m, b)
}
func (m *UserRating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRating.Marshal(b, m, deterministic)
}
func (m *UserRating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRating.Merge(m, src)
}
func (m *UserRating) XXX_Size() int {
	return xxx_messageInfo_UserRating.Size(m)
}
func (m *UserRating) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRating.DiscardUnknown(m)
}

var xxx_messageInfo_UserRating proto.InternalMessageInfo

func (m *UserRating) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *UserRating) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRating) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

type AgentRatingRequest struct {
	RequestId            string       `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string       `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	Rating               *AgentRating `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AgentRatingRequest) Reset()         { *m = AgentRatingRequest{} }
func (m *AgentRatingRequest) String() string { return proto.CompactTextString(m) }
func (*AgentRatingRequest) ProtoMessage()    {}
func (*AgentRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{17}
}

func (m *AgentRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRatingRequest.Unmarshal(m, b)
}
func (m *AgentRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRatingRequest.Marshal(b, m, deterministic)
}
func (m *AgentRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRatingRequest.Merge(m, src)
}
func (m *AgentRatingRequest) XXX_Size() int {
	return xxx_messageInfo_AgentRatingRequest.Size(m)
}
func (m *AgentRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRatingRequest proto.InternalMessageInfo

func (m *AgentRatingRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AgentRatingRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *AgentRatingRequest) GetRating() *AgentRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type UserRatingRequest struct {
	RequestId            string      `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string      `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	Rating               *UserRating `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserRatingRequest) Reset()         { *m = UserRatingRequest{} }
func (m *UserRatingRequest) String() string { return proto.CompactTextString(m) }
func (*UserRatingRequest) ProtoMessage()    {}
func (*UserRatingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{18}
}

func (m *UserRatingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRatingRequest.Unmarshal(m, b)
}
func (m *UserRatingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRatingRequest.Marshal(b, m, deterministic)
}
func (m *UserRatingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRatingRequest.Merge(m, src)
}
func (m *UserRatingRequest) XXX_Size() int {
	return xxx_messageInfo_UserRatingRequest.Size(m)
}
func (m *UserRatingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRatingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRatingRequest proto.InternalMessageInfo

func (m *UserRatingRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *UserRatingRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *UserRatingRequest) GetRating() *UserRating {
	if m != nil {
		return m.Rating
	}
	return nil
}

type AgentRatingResponse struct {
	Status               int32             `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string            `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string            `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	RatingList           []*AgentRating    `protobuf:"bytes,6,rep,name=ratingList,proto3" json:"ratingList,omitempty"`
	RatingTotal          *AgentRatingTotal `protobuf:"bytes,7,opt,name=ratingTotal,proto3" json:"ratingTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AgentRatingResponse) Reset()         { *m = AgentRatingResponse{} }
func (m *AgentRatingResponse) String() string { return proto.CompactTextString(m) }
func (*AgentRatingResponse) ProtoMessage()    {}
func (*AgentRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{19}
}

func (m *AgentRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRatingResponse.Unmarshal(m, b)
}
func (m *AgentRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRatingResponse.Marshal(b, m, deterministic)
}
func (m *AgentRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRatingResponse.Merge(m, src)
}
func (m *AgentRatingResponse) XXX_Size() int {
	return xxx_messageInfo_AgentRatingResponse.Size(m)
}
func (m *AgentRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRatingResponse proto.InternalMessageInfo

func (m *AgentRatingResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AgentRatingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AgentRatingResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AgentRatingResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *AgentRatingResponse) GetRatingList() []*AgentRating {
	if m != nil {
		return m.RatingList
	}
	return nil
}

func (m *AgentRatingResponse) GetRatingTotal() *AgentRatingTotal {
	if m != nil {
		return m.RatingTotal
	}
	return nil
}

type UserRatingResponse struct {
	Status               int32            `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string           `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string           `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	RatingList           []*UserRating    `protobuf:"bytes,6,rep,name=ratingList,proto3" json:"ratingList,omitempty"`
	RatingTotal          *UserRatingTotal `protobuf:"bytes,7,opt,name=ratingTotal,proto3" json:"ratingTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UserRatingResponse) Reset()         { *m = UserRatingResponse{} }
func (m *UserRatingResponse) String() string { return proto.CompactTextString(m) }
func (*UserRatingResponse) ProtoMessage()    {}
func (*UserRatingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{20}
}

func (m *UserRatingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRatingResponse.Unmarshal(m, b)
}
func (m *UserRatingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRatingResponse.Marshal(b, m, deterministic)
}
func (m *UserRatingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRatingResponse.Merge(m, src)
}
func (m *UserRatingResponse) XXX_Size() int {
	return xxx_messageInfo_UserRatingResponse.Size(m)
}
func (m *UserRatingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRatingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserRatingResponse proto.InternalMessageInfo

func (m *UserRatingResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserRatingResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserRatingResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *UserRatingResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *UserRatingResponse) GetRatingList() []*UserRating {
	if m != nil {
		return m.RatingList
	}
	return nil
}

func (m *UserRatingResponse) GetRatingTotal() *UserRatingTotal {
	if m != nil {
		return m.RatingTotal
	}
	return nil
}

type AgentRatingTotal struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	TotalRating          float64  `protobuf:"fixed64,2,opt,name=totalRating,proto3" json:"totalRating,omitempty"`
	TotalReviewer        float64  `protobuf:"fixed64,3,opt,name=totalReviewer,proto3" json:"totalReviewer,omitempty"`
	CoverageRating       float64  `protobuf:"fixed64,4,opt,name=coverageRating,proto3" json:"coverageRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentRatingTotal) Reset()         { *m = AgentRatingTotal{} }
func (m *AgentRatingTotal) String() string { return proto.CompactTextString(m) }
func (*AgentRatingTotal) ProtoMessage()    {}
func (*AgentRatingTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{21}
}

func (m *AgentRatingTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentRatingTotal.Unmarshal(m, b)
}
func (m *AgentRatingTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentRatingTotal.Marshal(b, m, deterministic)
}
func (m *AgentRatingTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentRatingTotal.Merge(m, src)
}
func (m *AgentRatingTotal) XXX_Size() int {
	return xxx_messageInfo_AgentRatingTotal.Size(m)
}
func (m *AgentRatingTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentRatingTotal.DiscardUnknown(m)
}

var xxx_messageInfo_AgentRatingTotal proto.InternalMessageInfo

func (m *AgentRatingTotal) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *AgentRatingTotal) GetTotalRating() float64 {
	if m != nil {
		return m.TotalRating
	}
	return 0
}

func (m *AgentRatingTotal) GetTotalReviewer() float64 {
	if m != nil {
		return m.TotalReviewer
	}
	return 0
}

func (m *AgentRatingTotal) GetCoverageRating() float64 {
	if m != nil {
		return m.CoverageRating
	}
	return 0
}

type UserRatingTotal struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TotalRating          float64  `protobuf:"fixed64,2,opt,name=totalRating,proto3" json:"totalRating,omitempty"`
	TotalReviewer        float64  `protobuf:"fixed64,3,opt,name=totalReviewer,proto3" json:"totalReviewer,omitempty"`
	CoverageRating       float64  `protobuf:"fixed64,4,opt,name=coverageRating,proto3" json:"coverageRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRatingTotal) Reset()         { *m = UserRatingTotal{} }
func (m *UserRatingTotal) String() string { return proto.CompactTextString(m) }
func (*UserRatingTotal) ProtoMessage()    {}
func (*UserRatingTotal) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{22}
}

func (m *UserRatingTotal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRatingTotal.Unmarshal(m, b)
}
func (m *UserRatingTotal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRatingTotal.Marshal(b, m, deterministic)
}
func (m *UserRatingTotal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRatingTotal.Merge(m, src)
}
func (m *UserRatingTotal) XXX_Size() int {
	return xxx_messageInfo_UserRatingTotal.Size(m)
}
func (m *UserRatingTotal) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRatingTotal.DiscardUnknown(m)
}

var xxx_messageInfo_UserRatingTotal proto.InternalMessageInfo

func (m *UserRatingTotal) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserRatingTotal) GetTotalRating() float64 {
	if m != nil {
		return m.TotalRating
	}
	return 0
}

func (m *UserRatingTotal) GetTotalReviewer() float64 {
	if m != nil {
		return m.TotalReviewer
	}
	return 0
}

func (m *UserRatingTotal) GetCoverageRating() float64 {
	if m != nil {
		return m.CoverageRating
	}
	return 0
}

type MasterConfigRequest struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string            `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	MasterConfig         *DataMasterConfig `protobuf:"bytes,3,opt,name=masterConfig,proto3" json:"masterConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MasterConfigRequest) Reset()         { *m = MasterConfigRequest{} }
func (m *MasterConfigRequest) String() string { return proto.CompactTextString(m) }
func (*MasterConfigRequest) ProtoMessage()    {}
func (*MasterConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{23}
}

func (m *MasterConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterConfigRequest.Unmarshal(m, b)
}
func (m *MasterConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterConfigRequest.Marshal(b, m, deterministic)
}
func (m *MasterConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterConfigRequest.Merge(m, src)
}
func (m *MasterConfigRequest) XXX_Size() int {
	return xxx_messageInfo_MasterConfigRequest.Size(m)
}
func (m *MasterConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterConfigRequest proto.InternalMessageInfo

func (m *MasterConfigRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *MasterConfigRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *MasterConfigRequest) GetMasterConfig() *DataMasterConfig {
	if m != nil {
		return m.MasterConfig
	}
	return nil
}

type MasterConfigResponse struct {
	Status               int32               `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string              `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string              `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	DataMasterConfig     *DataMasterConfig   `protobuf:"bytes,5,opt,name=dataMasterConfig,proto3" json:"dataMasterConfig,omitempty"`
	ListMasterConfig     []*DataMasterConfig `protobuf:"bytes,6,rep,name=listMasterConfig,proto3" json:"listMasterConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MasterConfigResponse) Reset()         { *m = MasterConfigResponse{} }
func (m *MasterConfigResponse) String() string { return proto.CompactTextString(m) }
func (*MasterConfigResponse) ProtoMessage()    {}
func (*MasterConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{24}
}

func (m *MasterConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterConfigResponse.Unmarshal(m, b)
}
func (m *MasterConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterConfigResponse.Marshal(b, m, deterministic)
}
func (m *MasterConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterConfigResponse.Merge(m, src)
}
func (m *MasterConfigResponse) XXX_Size() int {
	return xxx_messageInfo_MasterConfigResponse.Size(m)
}
func (m *MasterConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterConfigResponse proto.InternalMessageInfo

func (m *MasterConfigResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MasterConfigResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MasterConfigResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *MasterConfigResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *MasterConfigResponse) GetDataMasterConfig() *DataMasterConfig {
	if m != nil {
		return m.DataMasterConfig
	}
	return nil
}

func (m *MasterConfigResponse) GetListMasterConfig() []*DataMasterConfig {
	if m != nil {
		return m.ListMasterConfig
	}
	return nil
}

type DataMasterConfig struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParamKey             string   `protobuf:"bytes,2,opt,name=paramKey,proto3" json:"paramKey,omitempty"`
	ParamValue           string   `protobuf:"bytes,3,opt,name=paramValue,proto3" json:"paramValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMasterConfig) Reset()         { *m = DataMasterConfig{} }
func (m *DataMasterConfig) String() string { return proto.CompactTextString(m) }
func (*DataMasterConfig) ProtoMessage()    {}
func (*DataMasterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{25}
}

func (m *DataMasterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMasterConfig.Unmarshal(m, b)
}
func (m *DataMasterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMasterConfig.Marshal(b, m, deterministic)
}
func (m *DataMasterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMasterConfig.Merge(m, src)
}
func (m *DataMasterConfig) XXX_Size() int {
	return xxx_messageInfo_DataMasterConfig.Size(m)
}
func (m *DataMasterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMasterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DataMasterConfig proto.InternalMessageInfo

func (m *DataMasterConfig) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataMasterConfig) GetParamKey() string {
	if m != nil {
		return m.ParamKey
	}
	return ""
}

func (m *DataMasterConfig) GetParamValue() string {
	if m != nil {
		return m.ParamValue
	}
	return ""
}

type AdminRequest struct {
	RequestId            string     `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string     `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	Admin                *DataAdmin `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminRequest) Reset()         { *m = AdminRequest{} }
func (m *AdminRequest) String() string { return proto.CompactTextString(m) }
func (*AdminRequest) ProtoMessage()    {}
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{26}
}

func (m *AdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRequest.Unmarshal(m, b)
}
func (m *AdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRequest.Marshal(b, m, deterministic)
}
func (m *AdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRequest.Merge(m, src)
}
func (m *AdminRequest) XXX_Size() int {
	return xxx_messageInfo_AdminRequest.Size(m)
}
func (m *AdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRequest proto.InternalMessageInfo

func (m *AdminRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *AdminRequest) GetAdmin() *DataAdmin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type AdminResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string       `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string       `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	DataAdmin            *DataAdmin   `protobuf:"bytes,5,opt,name=dataAdmin,proto3" json:"dataAdmin,omitempty"`
	ListAdmin            []*DataAdmin `protobuf:"bytes,6,rep,name=listAdmin,proto3" json:"listAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminResponse) Reset()         { *m = AdminResponse{} }
func (m *AdminResponse) String() string { return proto.CompactTextString(m) }
func (*AdminResponse) ProtoMessage()    {}
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{27}
}

func (m *AdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminResponse.Unmarshal(m, b)
}
func (m *AdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminResponse.Marshal(b, m, deterministic)
}
func (m *AdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminResponse.Merge(m, src)
}
func (m *AdminResponse) XXX_Size() int {
	return xxx_messageInfo_AdminResponse.Size(m)
}
func (m *AdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminResponse proto.InternalMessageInfo

func (m *AdminResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdminResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AdminResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *AdminResponse) GetDataAdmin() *DataAdmin {
	if m != nil {
		return m.DataAdmin
	}
	return nil
}

func (m *AdminResponse) GetListAdmin() []*DataAdmin {
	if m != nil {
		return m.ListAdmin
	}
	return nil
}

type DataAdmin struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed              int64    `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,5,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,7,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,13,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	AccessId             string   `protobuf:"bytes,14,opt,name=accessId,proto3" json:"accessId,omitempty"`
	ResetCode            string   `protobuf:"bytes,15,opt,name=resetCode,proto3" json:"resetCode,omitempty"`
	ResetExpiredTime     int64    `protobuf:"varint,16,opt,name=resetExpiredTime,proto3" json:"resetExpiredTime,omitempty"`
	IdOfficeRegional     int32    `protobuf:"varint,17,opt,name=idOfficeRegional,proto3" json:"idOfficeRegional,omitempty"`
	PersonalNumber       string   `protobuf:"bytes,18,opt,name=personalNumber,proto3" json:"personalNumber,omitempty"`
	IsSuperAdmin         bool     `protobuf:"varint,19,opt,name=isSuperAdmin,proto3" json:"isSuperAdmin,omitempty"`
	Role                 string   `protobuf:"bytes,20,opt,name=role,proto3" json:"role,omitempty"`
	RoleId               int32    `protobuf:"varint,21,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAdmin) Reset()         { *m = DataAdmin{} }
func (m *DataAdmin) String() string { return proto.CompactTextString(m) }
func (*DataAdmin) ProtoMessage()    {}
func (*DataAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b9a4cd5d067c70b, []int{28}
}

func (m *DataAdmin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAdmin.Unmarshal(m, b)
}
func (m *DataAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAdmin.Marshal(b, m, deterministic)
}
func (m *DataAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAdmin.Merge(m, src)
}
func (m *DataAdmin) XXX_Size() int {
	return xxx_messageInfo_DataAdmin.Size(m)
}
func (m *DataAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_DataAdmin proto.InternalMessageInfo

func (m *DataAdmin) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DataAdmin) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *DataAdmin) GetRemoved() int64 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *DataAdmin) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataAdmin) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *DataAdmin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataAdmin) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DataAdmin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataAdmin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DataAdmin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DataAdmin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DataAdmin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DataAdmin) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *DataAdmin) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *DataAdmin) GetResetCode() string {
	if m != nil {
		return m.ResetCode
	}
	return ""
}

func (m *DataAdmin) GetResetExpiredTime() int64 {
	if m != nil {
		return m.ResetExpiredTime
	}
	return 0
}

func (m *DataAdmin) GetIdOfficeRegional() int32 {
	if m != nil {
		return m.IdOfficeRegional
	}
	return 0
}

func (m *DataAdmin) GetPersonalNumber() string {
	if m != nil {
		return m.PersonalNumber
	}
	return ""
}

func (m *DataAdmin) GetIsSuperAdmin() bool {
	if m != nil {
		return m.IsSuperAdmin
	}
	return false
}

func (m *DataAdmin) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DataAdmin) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseRequest)(nil), "proto.BaseRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.BaseRequest.BodyStringEntry")
	proto.RegisterMapType((map[string]string)(nil), "proto.BaseRequest.HeadersEntry")
	proto.RegisterType((*BaseResponse)(nil), "proto.BaseResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.BaseResponse.HeadersEntry")
	proto.RegisterType((*MessageProto)(nil), "proto.MessageProto")
	proto.RegisterType((*SessionRequest)(nil), "proto.SessionRequest")
	proto.RegisterType((*SessionResponse)(nil), "proto.SessionResponse")
	proto.RegisterType((*SessionData)(nil), "proto.SessionData")
	proto.RegisterType((*UserRequest)(nil), "proto.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
	proto.RegisterType((*DataUser)(nil), "proto.DataUser")
	proto.RegisterType((*OrderSummary)(nil), "proto.OrderSummary")
	proto.RegisterType((*OrderSummaryRequest)(nil), "proto.OrderSummaryRequest")
	proto.RegisterType((*OrderSummaryResponse)(nil), "proto.OrderSummaryResponse")
	proto.RegisterType((*OrderRequest)(nil), "proto.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "proto.OrderResponse")
	proto.RegisterType((*DataOrder)(nil), "proto.DataOrder")
	proto.RegisterType((*AgentRating)(nil), "proto.AgentRating")
	proto.RegisterType((*UserRating)(nil), "proto.UserRating")
	proto.RegisterType((*AgentRatingRequest)(nil), "proto.AgentRatingRequest")
	proto.RegisterType((*UserRatingRequest)(nil), "proto.UserRatingRequest")
	proto.RegisterType((*AgentRatingResponse)(nil), "proto.AgentRatingResponse")
	proto.RegisterType((*UserRatingResponse)(nil), "proto.UserRatingResponse")
	proto.RegisterType((*AgentRatingTotal)(nil), "proto.AgentRatingTotal")
	proto.RegisterType((*UserRatingTotal)(nil), "proto.UserRatingTotal")
	proto.RegisterType((*MasterConfigRequest)(nil), "proto.MasterConfigRequest")
	proto.RegisterType((*MasterConfigResponse)(nil), "proto.MasterConfigResponse")
	proto.RegisterType((*DataMasterConfig)(nil), "proto.DataMasterConfig")
	proto.RegisterType((*AdminRequest)(nil), "proto.AdminRequest")
	proto.RegisterType((*AdminResponse)(nil), "proto.AdminResponse")
	proto.RegisterType((*DataAdmin)(nil), "proto.DataAdmin")
}

func init() { proto.RegisterFile("proto/ambilin.proto", fileDescriptor_1b9a4cd5d067c70b) }

var fileDescriptor_1b9a4cd5d067c70b = []byte{
	// 3268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x3b, 0x5b, 0x6f, 0x1c, 0xb7,
	0xd5, 0xd9, 0xd5, 0xfd, 0xac, 0x6e, 0x1e, 0xc9, 0xf2, 0x58, 0xf1, 0x97, 0xe8, 0x9b, 0xe4, 0xf3,
	0xe7, 0x26, 0x8d, 0x9c, 0xaa, 0x17, 0x3b, 0x4e, 0xdc, 0x44, 0x17, 0x4b, 0x51, 0x23, 0xdb, 0xc2,
	0xc8, 0x71, 0x81, 0x3e, 0x14, 0xa0, 0x76, 0xa8, 0x5d, 0x42, 0xbb, 0xc3, 0xe9, 0x0c, 0x57, 0xb6,
	0x80, 0x06, 0xc8, 0x63, 0x5b, 0xe4, 0x07, 0xb4, 0x40, 0x9e, 0xfb, 0x0f, 0x8a, 0x3e, 0xf4, 0xad,
	0x6f, 0xfd, 0x05, 0x45, 0xdf, 0xfb, 0x52, 0xf4, 0x2f, 0xb4, 0x40, 0xc1, 0x43, 0x72, 0x96, 0xb3,
	0xbb, 0x4a, 0x43, 0xda, 0x6d, 0xd5, 0x27, 0x0d, 0x0f, 0xcf, 0x39, 0x3c, 0x3c, 0x3c, 0x37, 0xf2,
	0xac, 0x60, 0x29, 0xcb, 0xb9, 0xe0, 0xb7, 0x49, 0xf7, 0x98, 0x75, 0x58, 0xba, 0x8e, 0xa3, 0x60,
	0x02, 0xff, 0x44, 0xbf, 0xad, 0x43, 0x63, 0x8b, 0x14, 0x34, 0xa6, 0x3f, 0xe9, 0xd1, 0x42, 0x04,
	0x2b, 0x30, 0x29, 0x9e, 0x3f, 0x39, 0xcf, 0x68, 0x58, 0x5b, 0xab, 0xdd, 0x9a, 0x89, 0xf5, 0x28,
	0x78, 0x0f, 0xa6, 0xda, 0x94, 0x24, 0x34, 0x2f, 0xc2, 0xfa, 0xda, 0xd8, 0xad, 0xc6, 0xc6, 0xeb,
	0x8a, 0xcf, 0xba, 0x45, 0xbc, 0xfe, 0xb1, 0xc2, 0x78, 0x90, 0x8a, 0xfc, 0x3c, 0x36, 0xf8, 0x92,
	0x65, 0x46, 0x72, 0xd2, 0x2d, 0xc2, 0xb1, 0xb5, 0xda, 0xad, 0xd9, 0x58, 0x8f, 0x82, 0x2d, 0x80,
	0x63, 0x9e, 0x9c, 0x1f, 0x89, 0x9c, 0xa5, 0xad, 0x70, 0x1c, 0xb9, 0x46, 0x23, 0xb8, 0x6e, 0x95,
	0x48, 0x8a, 0xb1, 0x45, 0xb5, 0x7a, 0x0f, 0x66, 0xed, 0x45, 0x83, 0x45, 0x18, 0x3b, 0xa5, 0xe7,
	0x5a, 0x76, 0xf9, 0x19, 0x2c, 0xc3, 0xc4, 0x19, 0xe9, 0xf4, 0x68, 0x58, 0x47, 0x98, 0x1a, 0xdc,
	0xab, 0xdf, 0xad, 0xad, 0xde, 0x87, 0x85, 0x01, 0xd6, 0x2e, 0xe4, 0xd1, 0xef, 0x6b, 0x30, 0xab,
	0xc4, 0x2c, 0x32, 0x9e, 0x16, 0x34, 0x58, 0x85, 0xe9, 0x5c, 0x7f, 0x23, 0x87, 0xd9, 0xb8, 0x1c,
	0x07, 0xf7, 0x06, 0xd5, 0xb7, 0x56, 0xd9, 0xa8, 0xc2, 0xba, 0x40, 0x7f, 0xaf, 0x01, 0xb4, 0x85,
	0xc8, 0x8e, 0x04, 0x11, 0x3d, 0xa5, 0xc3, 0x89, 0xd8, 0x82, 0xbc, 0x88, 0x0e, 0xa2, 0x08, 0x66,
	0x1f, 0xd2, 0xa2, 0x20, 0x2d, 0x7a, 0x88, 0x56, 0x11, 0xc0, 0xb8, 0xa0, 0xcf, 0x85, 0x96, 0x1f,
	0xbf, 0xa3, 0x63, 0x98, 0x3f, 0xa2, 0x45, 0xc1, 0x78, 0x6a, 0x8c, 0x64, 0x19, 0x26, 0x04, 0x3f,
	0xa5, 0xa9, 0x5e, 0x43, 0x0d, 0x82, 0x1b, 0x30, 0x53, 0xb0, 0x56, 0x4a, 0x44, 0x2f, 0x37, 0x2b,
	0xf5, 0x01, 0x72, 0x36, 0x57, 0xe4, 0xfb, 0x09, 0x6e, 0x62, 0x26, 0xee, 0x03, 0xa2, 0x9f, 0xd7,
	0x60, 0xa1, 0x5c, 0x44, 0xeb, 0x6c, 0x05, 0x26, 0x0b, 0xb5, 0xe7, 0x1a, 0xee, 0x59, 0x8f, 0x82,
	0x10, 0xa6, 0xba, 0x4a, 0x66, 0xbd, 0x8a, 0x19, 0x06, 0x37, 0x61, 0x3c, 0x21, 0x82, 0x20, 0xfb,
	0xc6, 0x46, 0xa0, 0x55, 0xac, 0xf9, 0xee, 0x10, 0x41, 0x62, 0x9c, 0xaf, 0xca, 0x32, 0x3e, 0x28,
	0xcb, 0x67, 0xd0, 0xb0, 0x48, 0xe4, 0xb1, 0xf6, 0x0a, 0x9a, 0xa7, 0xa4, 0x6b, 0x7c, 0xa2, 0x1c,
	0x4b, 0x75, 0x21, 0x5c, 0xc9, 0x31, 0x6e, 0x60, 0x42, 0xfa, 0x8f, 0xda, 0x23, 0x7e, 0xcb, 0xad,
	0x48, 0x9a, 0x72, 0x35, 0x3d, 0x92, 0xb8, 0x39, 0xef, 0xd0, 0x70, 0x42, 0xe1, 0xca, 0xef, 0xe8,
	0xa7, 0xd0, 0xf8, 0xb4, 0xa0, 0xb9, 0xd1, 0x75, 0x45, 0xd6, 0xda, 0x80, 0xac, 0xc1, 0x5b, 0xb0,
	0xa8, 0x07, 0x5b, 0xe7, 0x47, 0x34, 0x3f, 0x63, 0x4d, 0x23, 0xcc, 0x10, 0x3c, 0x78, 0x03, 0xc6,
	0xe5, 0xb2, 0x5a, 0x3b, 0x0b, 0x5a, 0x3b, 0x72, 0x8f, 0xb8, 0x1e, 0x4e, 0x46, 0x7f, 0xae, 0xc1,
	0xac, 0x5a, 0xde, 0xfb, 0x14, 0xbe, 0xf2, 0xa4, 0x47, 0x4a, 0x3c, 0x7e, 0x81, 0xc4, 0x6f, 0xc3,
	0x74, 0xa2, 0xc5, 0x43, 0x15, 0x8d, 0x90, 0xba, 0x44, 0x90, 0xc8, 0x1d, 0x56, 0x08, 0x44, 0x9e,
	0x44, 0x1f, 0x1b, 0x46, 0x36, 0x08, 0xd1, 0xaf, 0x27, 0x61, 0xda, 0x80, 0xe5, 0x56, 0x9a, 0x39,
	0x25, 0x82, 0x2a, 0x05, 0x8f, 0xc5, 0x66, 0x28, 0x67, 0x7a, 0x59, 0x82, 0x33, 0x75, 0x35, 0xa3,
	0x87, 0x72, 0x26, 0xa7, 0x5d, 0x7e, 0x46, 0xd5, 0x16, 0xc7, 0x62, 0x33, 0x94, 0xdb, 0xd7, 0xe4,
	0x5b, 0xe7, 0xc6, 0xb8, 0x4a, 0x80, 0x9c, 0xd5, 0x2c, 0xb6, 0xce, 0xf5, 0xb1, 0xf7, 0x01, 0xc1,
	0x3c, 0xd4, 0x59, 0x12, 0x4e, 0x22, 0xb8, 0xce, 0x92, 0xd2, 0xbe, 0xa6, 0x2c, 0xfb, 0x0a, 0x61,
	0x8a, 0x24, 0x49, 0x4e, 0x8b, 0x22, 0x9c, 0x56, 0x8a, 0xd7, 0x43, 0xe9, 0x96, 0xb4, 0x4b, 0x58,
	0x27, 0x9c, 0x51, 0x6e, 0x89, 0x03, 0x09, 0xcd, 0xda, 0x3c, 0xa5, 0x21, 0x28, 0x28, 0x0e, 0x24,
	0x67, 0x7a, 0x2a, 0xb2, 0xb0, 0xa1, 0x38, 0xcb, 0xef, 0xe0, 0x4d, 0x98, 0x23, 0xcd, 0x26, 0xef,
	0xa5, 0xe2, 0x51, 0xaf, 0x7b, 0x4c, 0xf3, 0x70, 0x16, 0x27, 0xab, 0x40, 0xe9, 0x0f, 0x59, 0x9b,
	0x0b, 0xfe, 0x69, 0xde, 0x09, 0xe7, 0x94, 0x3f, 0x98, 0xb1, 0x65, 0x2c, 0xf3, 0x15, 0x63, 0xc1,
	0x43, 0x6f, 0xb1, 0x42, 0xe4, 0x44, 0x30, 0x9e, 0x6e, 0xf3, 0x84, 0x86, 0x0b, 0x88, 0x31, 0x04,
	0x97, 0xfc, 0x49, 0xb3, 0x49, 0x8b, 0x62, 0x3f, 0x09, 0x17, 0x15, 0x7f, 0x33, 0xc6, 0xbd, 0xb7,
	0x68, 0x2a, 0x0d, 0xeb, 0x8a, 0xde, 0xbb, 0x1a, 0xa2, 0xd6, 0x3b, 0x8c, 0xa6, 0xe2, 0x90, 0xa5,
	0x61, 0xa0, 0xb5, 0x6e, 0x00, 0x32, 0x84, 0x9e, 0xb0, 0xbc, 0x10, 0x07, 0xbc, 0xc5, 0xd2, 0x70,
	0x69, 0xad, 0x76, 0x6b, 0x3a, 0xb6, 0x20, 0xc6, 0xc7, 0x31, 0xef, 0x2d, 0xf7, 0x7d, 0x1c, 0x33,
	0xdf, 0x9b, 0x30, 0xd7, 0xea, 0x91, 0x9c, 0xa4, 0x82, 0xe7, 0x8f, 0xe4, 0x61, 0x5c, 0x55, 0x5a,
	0xa9, 0x00, 0x83, 0x9b, 0x30, 0xcf, 0x12, 0x9a, 0x0a, 0x26, 0xce, 0xb5, 0xf2, 0x56, 0x10, 0x6d,
	0x00, 0x2a, 0xe5, 0x3c, 0xa1, 0xf4, 0x90, 0x35, 0x4f, 0x7b, 0x59, 0x78, 0x4d, 0xc9, 0x59, 0x02,
	0xa4, 0x1c, 0xa7, 0x24, 0x7d, 0xc6, 0x3a, 0xfb, 0x49, 0x18, 0xa2, 0x7e, 0xca, 0xb1, 0xdc, 0xfb,
	0x29, 0x49, 0x9b, 0x64, 0x3f, 0x09, 0xaf, 0xe3, 0x94, 0x19, 0x4a, 0x9e, 0x19, 0xc9, 0x45, 0x8a,
	0x01, 0x66, 0x55, 0xf1, 0x2c, 0x01, 0x72, 0xef, 0x8a, 0x07, 0x0a, 0xff, 0x2a, 0x4e, 0x5b, 0x10,
	0x49, 0x8d, 0x8c, 0x70, 0xfa, 0x86, 0xa2, 0x2e, 0x01, 0xd1, 0x17, 0x63, 0x30, 0xfb, 0x38, 0x4f,
	0x68, 0x7e, 0xd4, 0xeb, 0x76, 0x49, 0x7e, 0x1e, 0xac, 0x41, 0x43, 0x5b, 0xf3, 0x0e, 0x11, 0x26,
	0x22, 0xda, 0x20, 0xcc, 0x03, 0x82, 0xe4, 0x02, 0xe7, 0x4d, 0x1e, 0x30, 0x00, 0xb9, 0x0d, 0x9a,
	0x2a, 0x5a, 0x15, 0x1b, 0xcc, 0x50, 0x2a, 0x3a, 0xa1, 0x19, 0x2f, 0x98, 0xd8, 0xec, 0x4a, 0x7b,
	0x43, 0xe7, 0xa9, 0xc7, 0x55, 0xa0, 0x5c, 0xbf, 0x68, 0xb3, 0x2c, 0x63, 0x69, 0x6b, 0x97, 0xaa,
	0xc8, 0x59, 0x8f, 0x6d, 0x50, 0x10, 0xc1, 0x2c, 0x4b, 0x8b, 0x5e, 0x4e, 0xd2, 0x26, 0x95, 0x28,
	0x93, 0x88, 0x52, 0x81, 0xd9, 0x86, 0x34, 0x55, 0x35, 0xa4, 0xb7, 0x60, 0x51, 0x70, 0x41, 0x3a,
	0x4f, 0x72, 0x92, 0x16, 0xa4, 0x29, 0xcd, 0x12, 0xfd, 0xac, 0x1e, 0x0f, 0xc1, 0x83, 0xbb, 0x70,
	0x6d, 0x10, 0x76, 0xd4, 0x43, 0x5b, 0x45, 0x17, 0xac, 0xc7, 0x17, 0x4d, 0x07, 0xdf, 0x83, 0x95,
	0xc1, 0xa9, 0x5d, 0xc2, 0x3a, 0x34, 0x41, 0x2f, 0xad, 0xc7, 0x17, 0xcc, 0x46, 0x5f, 0xd4, 0x60,
	0xc9, 0x3e, 0x8e, 0x97, 0x9f, 0x25, 0xde, 0xae, 0x54, 0x6b, 0x8d, 0x8d, 0x25, 0x1d, 0x44, 0x2b,
	0xab, 0x6a, 0x94, 0xe8, 0x77, 0x35, 0x58, 0xae, 0x8a, 0x73, 0x09, 0xb2, 0xc6, 0xff, 0xeb, 0x2a,
	0x60, 0xe2, 0x62, 0xf9, 0x11, 0x21, 0xfa, 0x4c, 0x9b, 0xf6, 0x7f, 0x28, 0xd5, 0xfe, 0xb5, 0x06,
	0x73, 0x7a, 0xfd, 0x4b, 0xa0, 0xb5, 0x75, 0x98, 0x91, 0x4a, 0x41, 0x81, 0xb4, 0xea, 0x16, 0x2d,
	0xb9, 0x95, 0xa0, 0x7d, 0x14, 0x89, 0x2f, 0xb3, 0xa9, 0xc2, 0x57, 0xf9, 0x76, 0x04, 0x7e, 0x89,
	0x12, 0xfd, 0x05, 0x60, 0xa6, 0x9c, 0xb8, 0xc4, 0x29, 0xb7, 0x5f, 0xaa, 0x4d, 0x55, 0x4a, 0x35,
	0x2b, 0x62, 0x4c, 0x57, 0x23, 0xc6, 0x50, 0xdc, 0x9a, 0xf9, 0x1a, 0x71, 0x0b, 0x86, 0xe3, 0xd6,
	0x4d, 0x98, 0x37, 0xc3, 0x87, 0x54, 0xb4, 0x79, 0x82, 0xc9, 0x79, 0x22, 0x1e, 0x80, 0x06, 0xef,
	0xc2, 0x12, 0x47, 0x63, 0x46, 0xe3, 0xd8, 0xee, 0x15, 0x82, 0x77, 0x75, 0xb2, 0x9e, 0x88, 0x47,
	0x4d, 0x49, 0x0d, 0x20, 0x18, 0xf3, 0x9b, 0xca, 0xd9, 0x7d, 0x80, 0x5c, 0x37, 0xcb, 0x79, 0x4b,
	0x96, 0x10, 0x3a, 0x2f, 0xa9, 0xe4, 0x3d, 0x00, 0x95, 0x89, 0x04, 0x89, 0x0e, 0x88, 0xa0, 0x39,
	0xa6, 0xef, 0x99, 0xd8, 0x82, 0x48, 0x6b, 0xa3, 0x85, 0x60, 0x5d, 0xa9, 0xd8, 0xcd, 0x3c, 0x67,
	0x67, 0xa4, 0xa3, 0x13, 0xf8, 0x10, 0x3c, 0xb8, 0x05, 0x0b, 0x25, 0x4c, 0x2f, 0xaa, 0x12, 0xfa,
	0x20, 0x58, 0x6a, 0xb7, 0xa9, 0xf7, 0x71, 0xd8, 0x21, 0x4d, 0xaa, 0x93, 0x7b, 0x15, 0x28, 0xf9,
	0x19, 0xc0, 0xa6, 0x2e, 0x8e, 0x96, 0x14, 0xbf, 0x01, 0xb0, 0x94, 0xd2, 0x80, 0x0e, 0x88, 0x60,
	0xa2, 0x97, 0xa8, 0x94, 0x5f, 0x8f, 0x87, 0xe0, 0xc1, 0x37, 0xe1, 0x4a, 0x09, 0xe3, 0x69, 0x4b,
	0x21, 0x5f, 0x45, 0xe4, 0xe1, 0x09, 0x2c, 0x9f, 0xa4, 0x49, 0x94, 0x6c, 0x57, 0x94, 0x1d, 0x54,
	0x80, 0x52, 0xdb, 0x0a, 0x50, 0x32, 0xbc, 0x86, 0x68, 0x03, 0x50, 0x29, 0xa7, 0x75, 0x94, 0x9b,
	0x72, 0x52, 0x97, 0x04, 0x43, 0x70, 0xb4, 0x7f, 0x6e, 0x7c, 0xf1, 0x3a, 0xb2, 0xeb, 0x03, 0x64,
	0x3e, 0x24, 0x68, 0x83, 0xfa, 0x06, 0xb9, 0x8a, 0xe5, 0x4f, 0x05, 0x26, 0xad, 0x93, 0x3e, 0xcf,
	0x58, 0x4e, 0x93, 0x27, 0x4c, 0x57, 0x09, 0x63, 0xb1, 0x0d, 0xc2, 0x73, 0xe0, 0xdd, 0xac, 0x43,
	0x85, 0xc6, 0xb9, 0x81, 0x38, 0x55, 0xa0, 0x2c, 0x60, 0x12, 0x56, 0x08, 0x99, 0x66, 0xc3, 0xff,
	0x41, 0x41, 0xca, 0xb1, 0xe2, 0x90, 0x9e, 0xb0, 0xbc, 0xbb, 0xd5, 0x13, 0x82, 0xa7, 0xe1, 0x6b,
	0x28, 0x48, 0x15, 0x18, 0xac, 0x43, 0x50, 0x01, 0xa8, 0x9d, 0xbf, 0x8e, 0xa8, 0x23, 0x66, 0xa4,
	0x37, 0xd8, 0x3b, 0xd9, 0x4f, 0xcf, 0x48, 0x87, 0x25, 0xe1, 0x1a, 0x12, 0x8c, 0x9a, 0x2a, 0xbd,
	0x01, 0xab, 0xd0, 0xff, 0xb5, 0xbc, 0x01, 0xcb, 0xcf, 0x35, 0x68, 0xb0, 0x62, 0x5b, 0x52, 0x25,
	0xfc, 0x59, 0x1a, 0x46, 0xc8, 0xc7, 0x06, 0xc9, 0x15, 0x3b, 0xbc, 0x89, 0x05, 0xeb, 0x0e, 0x2d,
	0x9a, 0x39, 0xcb, 0xb0, 0x48, 0x78, 0x03, 0x39, 0x8d, 0x9a, 0x92, 0x3c, 0x71, 0x81, 0x5d, 0x96,
	0xb2, 0xa2, 0x1d, 0xbe, 0xa9, 0xb4, 0x6b, 0x81, 0xa4, 0xa5, 0x59, 0xca, 0x7e, 0xf0, 0x5c, 0xd0,
	0x34, 0x09, 0xff, 0x0f, 0x39, 0x0e, 0x4f, 0x48, 0x4f, 0xec, 0xe5, 0x9d, 0xfd, 0xf4, 0x8c, 0xcb,
	0x88, 0x7e, 0x53, 0x79, 0x62, 0x1f, 0x12, 0xfd, 0xbd, 0x06, 0x0d, 0xd4, 0x4e, 0x4c, 0x04, 0x4b,
	0x5b, 0x32, 0x76, 0xe1, 0x62, 0x65, 0x5a, 0x33, 0x43, 0x3b, 0xaa, 0xd5, 0xab, 0x51, 0x6d, 0x05,
	0x26, 0x73, 0xa4, 0xd6, 0x2f, 0x0e, 0x7a, 0x24, 0xed, 0xf7, 0x94, 0x0a, 0x9a, 0x11, 0x41, 0xd2,
	0x1f, 0x92, 0x53, 0xd1, 0xc3, 0x80, 0x3b, 0x1d, 0x0f, 0x40, 0xb1, 0xac, 0xa4, 0x05, 0xcf, 0x48,
	0x4a, 0x52, 0x8c, 0xba, 0xd3, 0x71, 0x1f, 0x80, 0x45, 0x29, 0x15, 0xb4, 0xc3, 0x04, 0x23, 0x29,
	0x46, 0xdf, 0xe9, 0xd8, 0x82, 0x28, 0xea, 0x9c, 0x64, 0xac, 0x4d, 0x52, 0x0c, 0xc4, 0x48, 0xad,
	0x01, 0x86, 0x3a, 0x27, 0x69, 0x8b, 0xa4, 0x3a, 0x1c, 0x5b, 0x90, 0xe8, 0x29, 0x00, 0xe6, 0xd9,
	0x7f, 0xb6, 0xfb, 0x7e, 0xac, 0xaf, 0x57, 0x62, 0xfd, 0x05, 0x7b, 0x8f, 0x7e, 0x51, 0x83, 0xc0,
	0xd2, 0xeb, 0xcb, 0xaf, 0x1b, 0xde, 0xaa, 0x2c, 0xdc, 0x7f, 0xc2, 0xb0, 0x17, 0x35, 0xc2, 0xfc,
	0xac, 0x06, 0x57, 0xfa, 0xbb, 0x7c, 0xf9, 0xb2, 0x7c, 0x63, 0x40, 0x96, 0x2b, 0x5a, 0x16, 0x6b,
	0x4d, 0x23, 0xca, 0xe7, 0x75, 0x58, 0xaa, 0xe8, 0xe5, 0x12, 0xd4, 0x33, 0x1b, 0x00, 0x4a, 0xba,
	0x03, 0x56, 0x08, 0x5d, 0xa0, 0x8c, 0x52, 0xa7, 0x85, 0x15, 0xbc, 0x07, 0x0d, 0x35, 0x7a, 0x22,
	0xab, 0x6f, 0xb4, 0xbb, 0xc6, 0xc6, 0xb5, 0x61, 0x22, 0x9c, 0x8e, 0x6d, 0x5c, 0xe9, 0x72, 0x81,
	0x7d, 0x1a, 0x97, 0x40, 0x03, 0xdf, 0x1a, 0xa1, 0x81, 0x11, 0x87, 0x68, 0x2b, 0xe0, 0xee, 0x28,
	0x05, 0xac, 0x0c, 0xd1, 0x8c, 0xd8, 0xff, 0x97, 0x35, 0x58, 0x1c, 0xd4, 0x90, 0x1d, 0x5d, 0x6a,
	0xd5, 0xe8, 0xb2, 0x06, 0x0d, 0xbc, 0xe1, 0x28, 0x6c, 0xd4, 0x41, 0x2d, 0xb6, 0x41, 0x32, 0x5b,
	0xa8, 0x21, 0x3d, 0x63, 0xf4, 0x99, 0xae, 0xa5, 0x6b, 0x71, 0x15, 0x28, 0xa3, 0x51, 0x93, 0x9f,
	0xd1, 0x9c, 0xb4, 0xa8, 0x66, 0x35, 0x8e, 0x68, 0x03, 0xd0, 0xe8, 0x57, 0x35, 0x58, 0x18, 0x90,
	0xdf, 0xf2, 0xfe, 0x5a, 0xc5, 0xfb, 0xff, 0xdd, 0xb2, 0x7d, 0x59, 0x83, 0xa5, 0x87, 0xa4, 0x10,
	0x32, 0x01, 0xa5, 0x27, 0xec, 0x5f, 0xe0, 0xca, 0xef, 0xc3, 0x6c, 0xd7, 0x5a, 0x40, 0x3b, 0xf4,
	0x35, 0xab, 0x5c, 0xaf, 0xac, 0x5f, 0x41, 0x8e, 0xbe, 0xac, 0xc3, 0x72, 0x55, 0xbc, 0x4b, 0x60,
	0xdb, 0xdb, 0xb0, 0x98, 0x0c, 0x88, 0xad, 0x2f, 0x2d, 0x17, 0xee, 0x6a, 0x88, 0x40, 0x32, 0x91,
	0xf7, 0x93, 0x0a, 0x13, 0xe5, 0x26, 0x17, 0x33, 0x19, 0x24, 0x88, 0x7e, 0x0c, 0x8b, 0x83, 0x58,
	0xfa, 0x4e, 0xa1, 0xb4, 0x22, 0xef, 0x14, 0xab, 0x30, 0x8d, 0x17, 0xe6, 0x4f, 0xe8, 0xb9, 0x56,
	0x49, 0x39, 0x96, 0xb9, 0x0c, 0xbf, 0x9f, 0xe2, 0x03, 0xbd, 0x52, 0x8a, 0x05, 0x89, 0x3e, 0xaf,
	0xc1, 0xec, 0x66, 0xd2, 0x65, 0xe9, 0xcb, 0x37, 0x8b, 0x9b, 0x30, 0x41, 0x24, 0x67, 0x6d, 0x0f,
	0xf6, 0xf5, 0x4d, 0xad, 0xa8, 0xa6, 0xf1, 0xa2, 0xaa, 0x45, 0xb8, 0x3c, 0x17, 0x55, 0x14, 0x68,
	0xc4, 0x45, 0x55, 0x09, 0xda, 0x47, 0x31, 0x17, 0x55, 0x85, 0x3f, 0x7c, 0x51, 0xd5, 0xf8, 0x25,
	0x4a, 0xf4, 0xa7, 0x71, 0x75, 0x51, 0x55, 0xd4, 0xff, 0x7d, 0x17, 0x55, 0xf3, 0x66, 0x3c, 0x3d,
	0xfa, 0xcd, 0x78, 0xe6, 0x82, 0x37, 0x63, 0xb0, 0xdf, 0x8c, 0xd1, 0x60, 0x8b, 0xe2, 0x19, 0xcf,
	0x13, 0xfd, 0x42, 0x5c, 0x8e, 0xfb, 0xef, 0xc9, 0xb3, 0xf6, 0x7b, 0xf2, 0x57, 0xbd, 0x0a, 0xdb,
	0x2f, 0xba, 0xf3, 0x03, 0x2f, 0xba, 0x68, 0x17, 0x05, 0x15, 0xe5, 0x93, 0x30, 0xda, 0x85, 0x06,
	0x28, 0xbb, 0x28, 0xa8, 0x78, 0x60, 0xdd, 0x4d, 0x16, 0x51, 0xa5, 0x43, 0x70, 0x89, 0xcb, 0x92,
	0xc7, 0x27, 0x27, 0xac, 0x49, 0x63, 0xda, 0x62, 0x3c, 0x25, 0x1d, 0xbc, 0x53, 0x4e, 0xc4, 0x43,
	0x70, 0xbc, 0xf2, 0xd2, 0xbc, 0x90, 0xdf, 0xfa, 0xb5, 0x56, 0xdd, 0x2a, 0x07, 0xa0, 0xf8, 0x94,
	0x58, 0x1c, 0xf5, 0x32, 0x79, 0x7d, 0xec, 0x96, 0x2f, 0xc7, 0x15, 0x58, 0xd9, 0xc3, 0x59, 0xee,
	0xf7, 0x70, 0xb0, 0x80, 0xe4, 0x1d, 0xba, 0x9f, 0xe0, 0x6d, 0x51, 0x16, 0x90, 0x38, 0xda, 0xf8,
	0x25, 0x40, 0x63, 0xb3, 0x27, 0xda, 0xc6, 0x96, 0xf7, 0x60, 0x19, 0x99, 0x3c, 0x95, 0x17, 0x13,
	0x22, 0xa8, 0xee, 0x3b, 0x05, 0x57, 0xab, 0xad, 0x2b, 0xed, 0xfa, 0xab, 0x2b, 0x83, 0x60, 0xe5,
	0x8e, 0xd1, 0x2b, 0xc1, 0x1d, 0x00, 0x64, 0xa4, 0x9e, 0xb3, 0x83, 0xe1, 0x2e, 0xea, 0xea, 0xd2,
	0x88, 0x86, 0x63, 0xf4, 0x4a, 0xf0, 0x11, 0x2c, 0x21, 0xe1, 0x2e, 0xcf, 0x5b, 0x5c, 0x1c, 0x9a,
	0x43, 0x76, 0xe0, 0xf0, 0x21, 0x04, 0x26, 0x38, 0x50, 0x2f, 0x06, 0x7b, 0xb0, 0x3a, 0xcc, 0xc0,
	0x68, 0xc4, 0x67, 0x2f, 0xdb, 0x6d, 0x92, 0xb6, 0xa8, 0x8f, 0x28, 0x77, 0xa1, 0x61, 0xd4, 0xc8,
	0x7b, 0xc2, 0x85, 0xf2, 0x07, 0x70, 0xcd, 0x3c, 0xb7, 0xbc, 0xf0, 0x61, 0xde, 0x83, 0xb9, 0xed,
	0xf2, 0x75, 0xc1, 0xf1, 0x3c, 0xbf, 0x0f, 0x57, 0x0c, 0xed, 0x36, 0x06, 0x96, 0x43, 0x6f, 0xfa,
	0xa7, 0x34, 0x67, 0x27, 0xe7, 0xfe, 0xf4, 0xfa, 0x18, 0xbc, 0xe9, 0xb5, 0x49, 0xba, 0xd1, 0xbf,
	0x0f, 0xf3, 0x96, 0xee, 0x1c, 0x0f, 0x51, 0xba, 0xa3, 0x2c, 0x50, 0x5f, 0x8a, 0x3b, 0xaa, 0xe7,
	0x1c, 0x0f, 0x77, 0x44, 0x09, 0x50, 0xf7, 0x8f, 0x45, 0xe6, 0xcc, 0xe1, 0xae, 0xbe, 0xfa, 0xbb,
	0xef, 0xfe, 0x3d, 0x98, 0x3d, 0x54, 0x5d, 0x23, 0xe7, 0x45, 0x37, 0x61, 0x7e, 0x8f, 0x0a, 0x99,
	0x35, 0x7d, 0x55, 0xb6, 0xf1, 0x87, 0x05, 0xd5, 0xf7, 0x36, 0xa1, 0xf1, 0xbb, 0x30, 0xbd, 0x47,
	0xb1, 0x59, 0x5b, 0x94, 0x92, 0x58, 0x7d, 0xf1, 0x52, 0x12, 0xbb, 0x59, 0x1d, 0xbd, 0x12, 0x7c,
	0x07, 0xa6, 0x34, 0x99, 0x0b, 0xd5, 0x1d, 0x00, 0xe5, 0x2d, 0x1e, 0x84, 0x9f, 0x62, 0x86, 0xf6,
	0x20, 0xdc, 0xa1, 0x1d, 0xea, 0x4e, 0x78, 0x1f, 0x16, 0x31, 0x44, 0xe9, 0x5d, 0xe2, 0x0b, 0xae,
	0xc3, 0x49, 0xed, 0xc3, 0x0d, 0x43, 0x2e, 0x6f, 0x7c, 0xc6, 0x57, 0x0e, 0x75, 0xde, 0x73, 0x61,
	0x75, 0x00, 0xaf, 0x8f, 0x64, 0xa5, 0x6c, 0xa8, 0x68, 0xb3, 0xcc, 0x2b, 0x78, 0xe3, 0x39, 0x94,
	0x4f, 0xd7, 0x1e, 0x79, 0xc4, 0x78, 0x6f, 0x29, 0x90, 0x6a, 0x78, 0x7f, 0x7d, 0x46, 0xdb, 0xb0,
	0x62, 0x36, 0xb6, 0x43, 0x05, 0x61, 0x1d, 0x1f, 0x69, 0xcc, 0x7e, 0x94, 0x79, 0xbc, 0x08, 0x07,
	0x65, 0x27, 0x2f, 0xc2, 0x41, 0x9f, 0x90, 0x3e, 0x19, 0x17, 0x0e, 0xbb, 0x70, 0xbd, 0x54, 0x45,
	0x79, 0xcb, 0xf1, 0xe0, 0xb3, 0x05, 0x57, 0xab, 0x2a, 0xf5, 0xe0, 0x61, 0x0a, 0x0d, 0x9d, 0xd7,
	0xfc, 0x19, 0xa8, 0x23, 0x79, 0x01, 0x06, 0xea, 0x44, 0x3c, 0x18, 0x6c, 0xc2, 0xb2, 0x39, 0x47,
	0xd4, 0x68, 0xd1, 0x3e, 0xe6, 0xc4, 0xad, 0x44, 0xb9, 0x0f, 0x8b, 0x16, 0x8b, 0xc3, 0x9c, 0x77,
	0xb9, 0x67, 0x7e, 0x2d, 0xcf, 0xc2, 0xd1, 0xc9, 0x2c, 0x7a, 0xf3, 0xf9, 0x31, 0x2b, 0x04, 0xcf,
	0xcf, 0x3d, 0x13, 0xb5, 0x3a, 0x0f, 0x47, 0x0f, 0x2d, 0xab, 0x04, 0x72, 0xc6, 0x7b, 0x39, 0x13,
	0x54, 0xb5, 0x03, 0xdc, 0xbc, 0xa3, 0x2f, 0x41, 0x87, 0x93, 0xe4, 0xb0, 0x8d, 0x3f, 0x81, 0xf3,
	0xe2, 0xa0, 0x4d, 0xc2, 0x95, 0xc3, 0x4e, 0xbf, 0x6c, 0xdc, 0xa3, 0xe2, 0x11, 0x17, 0xec, 0x84,
	0xa9, 0xfe, 0x81, 0x0b, 0x97, 0x07, 0x10, 0x1a, 0x2e, 0x31, 0x25, 0x89, 0x2f, 0x1b, 0xeb, 0x6c,
	0xd5, 0x76, 0x3c, 0x19, 0x6d, 0xfc, 0x06, 0xcc, 0x8f, 0x46, 0xca, 0x7b, 0x0e, 0xec, 0x51, 0x61,
	0x7e, 0x42, 0xb2, 0x3a, 0xaa, 0x25, 0xaf, 0x39, 0xbe, 0x3a, 0x72, 0xce, 0xaa, 0x6e, 0x66, 0xf6,
	0xa8, 0xea, 0x6b, 0x15, 0x41, 0xa5, 0xb5, 0x6f, 0x18, 0x2c, 0x57, 0x81, 0x56, 0xc2, 0x9d, 0x36,
	0x94, 0x6e, 0x84, 0xf7, 0xa0, 0xa1, 0x22, 0x8e, 0x1f, 0xad, 0x32, 0x6e, 0x3f, 0x5a, 0x75, 0x0a,
	0x1e, 0xb4, 0x96, 0x61, 0x1e, 0xf5, 0x8e, 0xbb, 0x4c, 0xef, 0xdb, 0xd7, 0xb4, 0x65, 0x90, 0x70,
	0xe6, 0x60, 0xc5, 0xba, 0x6d, 0xd5, 0xb6, 0x73, 0x66, 0xf1, 0x31, 0xbc, 0x6a, 0x79, 0xc7, 0x81,
	0xf9, 0x2d, 0xc1, 0x61, 0xce, 0xf1, 0x47, 0x34, 0x9e, 0xc2, 0xe0, 0xb5, 0x44, 0xf7, 0x3d, 0xfd,
	0x34, 0xb2, 0x4d, 0xd2, 0x26, 0x75, 0xd7, 0xc8, 0x87, 0x10, 0xf4, 0x85, 0xa0, 0xcd, 0x53, 0x67,
	0x06, 0x8f, 0x21, 0xc2, 0x28, 0x67, 0xf2, 0xb9, 0xd2, 0xc3, 0x66, 0x9a, 0xe8, 0xf8, 0xeb, 0xcc,
	0xf0, 0xbe, 0x7e, 0xb4, 0xdf, 0x6c, 0x36, 0x69, 0x26, 0xbc, 0xc9, 0x55, 0xab, 0xde, 0x99, 0xfc,
	0x03, 0x58, 0x50, 0xdb, 0xe1, 0x2c, 0x6d, 0x39, 0x53, 0xcb, 0x92, 0x42, 0x52, 0x6b, 0xe3, 0xda,
	0xe6, 0x09, 0x75, 0xe6, 0x21, 0x2b, 0x3d, 0xc9, 0x43, 0x39, 0xa9, 0xfa, 0xa5, 0x86, 0x8f, 0x95,
	0x9a, 0x53, 0xd9, 0xa5, 0xd4, 0xfa, 0xcd, 0x96, 0x2b, 0xa7, 0x8d, 0xbf, 0x4d, 0xc2, 0x9c, 0x6a,
	0x0a, 0x98, 0xc0, 0x79, 0x00, 0x57, 0x54, 0xf0, 0xb1, 0xdb, 0xb9, 0xd7, 0x47, 0xb4, 0xb1, 0x34,
	0xe3, 0xd5, 0x51, 0x53, 0xa5, 0xa4, 0x0f, 0x61, 0xb9, 0x5a, 0x5e, 0x9b, 0x0e, 0xe9, 0x70, 0x57,
	0x48, 0xf3, 0xbb, 0x3e, 0x62, 0xc6, 0x7a, 0xf3, 0x58, 0xd8, 0xa3, 0xc2, 0x5a, 0xaa, 0xf0, 0x17,
	0xed, 0x11, 0x2c, 0x55, 0x79, 0xa9, 0x1e, 0x8d, 0x37, 0xbf, 0x4f, 0x20, 0xb0, 0xea, 0x13, 0x23,
	0x9e, 0xe7, 0x46, 0x1f, 0xc3, 0xca, 0x10, 0x33, 0xdd, 0xe1, 0xf2, 0x63, 0xb8, 0x0b, 0xd7, 0xab,
	0xaf, 0x34, 0xf6, 0xf1, 0xfa, 0x45, 0x94, 0x3d, 0x5a, 0x1e, 0x82, 0x5f, 0x21, 0x55, 0x32, 0x50,
	0x3b, 0x73, 0xbc, 0x24, 0xa0, 0x27, 0x8e, 0xb2, 0x2d, 0x9f, 0x78, 0xe0, 0xb5, 0x15, 0xf3, 0x74,
	0xe2, 0xbd, 0x8f, 0x8d, 0x3f, 0x06, 0xb0, 0x58, 0xd6, 0xe4, 0x7d, 0x0f, 0x94, 0x46, 0x5e, 0x69,
	0xef, 0x18, 0xcb, 0x1b, 0xd1, 0xb4, 0x2b, 0xeb, 0x97, 0x51, 0x1d, 0xb3, 0xb2, 0x7e, 0xc1, 0x4b,
	0x44, 0xbf, 0x7e, 0xb1, 0xdb, 0x3b, 0x65, 0x4a, 0xaf, 0x34, 0x5c, 0xca, 0xfa, 0x45, 0x3d, 0x39,
	0x3b, 0x11, 0x96, 0xf5, 0x8b, 0x1f, 0xad, 0x0e, 0x8d, 0x5e, 0xb4, 0xaa, 0x7e, 0xf1, 0xa0, 0xbd,
	0x53, 0xa9, 0x17, 0xdd, 0xde, 0xb0, 0xf4, 0x55, 0x75, 0x87, 0xb0, 0xce, 0xb9, 0x63, 0x32, 0xd3,
	0xa4, 0x0f, 0x9e, 0xd3, 0x66, 0x4f, 0xb0, 0x33, 0xea, 0xe8, 0x8a, 0x9a, 0xfc, 0x71, 0x46, 0xd5,
	0xcf, 0xd9, 0xdd, 0xbc, 0x48, 0x89, 0xfe, 0x84, 0x67, 0x68, 0xc5, 0x4e, 0xa6, 0x7f, 0x07, 0x60,
	0x97, 0xa5, 0x89, 0x3b, 0xe1, 0x87, 0x10, 0x48, 0x42, 0xd5, 0x1d, 0xd9, 0xca, 0x49, 0xda, 0x6c,
	0x53, 0x57, 0xa7, 0xeb, 0x33, 0x30, 0xed, 0x95, 0xc2, 0x7d, 0xdb, 0xba, 0x9c, 0x71, 0xbb, 0xcb,
	0xbe, 0xaf, 0x5e, 0x1d, 0xd5, 0x7b, 0x82, 0x2b, 0xf1, 0x5d, 0xe3, 0x16, 0x3e, 0x94, 0xfa, 0x05,
	0xc1, 0x83, 0x52, 0xdf, 0x13, 0x3d, 0xae, 0xed, 0x3b, 0xfc, 0x59, 0x2a, 0x6f, 0xa9, 0x5e, 0xd6,
	0xf9, 0x11, 0x2c, 0x19, 0xfa, 0x17, 0x32, 0x4f, 0x99, 0xcd, 0x74, 0xdb, 0xcb, 0xd9, 0x35, 0xf0,
	0x9c, 0xbc, 0x18, 0x7c, 0x00, 0x0b, 0xfd, 0xe7, 0x59, 0x1f, 0xea, 0xfe, 0x1b, 0xad, 0x0f, 0x75,
	0xff, 0xa1, 0xd6, 0x99, 0xfa, 0x0e, 0x00, 0x96, 0xfa, 0x0f, 0xba, 0x8e, 0xef, 0x2c, 0xf2, 0xb6,
	0x21, 0x09, 0x0f, 0xab, 0x0d, 0x49, 0x47, 0x03, 0x57, 0x1d, 0x18, 0xd7, 0x47, 0x89, 0xbe, 0x99,
	0x7a, 0x50, 0x6a, 0x67, 0x7e, 0x48, 0xd3, 0x9e, 0x0b, 0xe5, 0x3d, 0x98, 0x33, 0x57, 0x3c, 0x8c,
	0x25, 0x7e, 0xab, 0xc6, 0xbc, 0x43, 0x1d, 0xdd, 0xca, 0xa2, 0x94, 0x77, 0x42, 0xd6, 0x74, 0x97,
	0x5a, 0x59, 0xb6, 0xeb, 0xda, 0x65, 0xcf, 0xc1, 0x83, 0x50, 0xd9, 0xb3, 0x07, 0xa1, 0x3a, 0x57,
	0x57, 0x42, 0xe5, 0xc0, 0xfa, 0x92, 0xb9, 0xd9, 0x14, 0xec, 0x8c, 0x09, 0x97, 0xdc, 0xba, 0xf5,
	0xee, 0x8f, 0xd6, 0x5b, 0x4c, 0xb4, 0x7b, 0xc7, 0xeb, 0x4d, 0xde, 0xbd, 0x9d, 0xd0, 0x33, 0xfd,
	0xbf, 0xc8, 0xb7, 0x8f, 0x79, 0xf2, 0x8e, 0xfe, 0x7e, 0xa7, 0xc9, 0xbb, 0x5d, 0x9e, 0xde, 0x46,
	0x06, 0xc7, 0x93, 0xf8, 0xe7, 0xdb, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xda, 0xe4, 0xdb,
	0xbc, 0x3c, 0x00, 0x00,
}
