// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//for admin
type AdminLoginRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ResCaptcha           string   `protobuf:"bytes,4,opt,name=resCaptcha,proto3" json:"resCaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminLoginRequest) Reset()         { *m = AdminLoginRequest{} }
func (m *AdminLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AdminLoginRequest) ProtoMessage()    {}
func (*AdminLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{0}
}

func (m *AdminLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminLoginRequest.Unmarshal(m, b)
}
func (m *AdminLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminLoginRequest.Marshal(b, m, deterministic)
}
func (m *AdminLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminLoginRequest.Merge(m, src)
}
func (m *AdminLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AdminLoginRequest.Size(m)
}
func (m *AdminLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminLoginRequest proto.InternalMessageInfo

func (m *AdminLoginRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminLoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AdminLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminLoginRequest) GetResCaptcha() string {
	if m != nil {
		return m.ResCaptcha
	}
	return ""
}

type AdminLoginResponse struct {
	RequestId            string     `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Status               int32      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Token                string     `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	DataAdmin            *DataAdmin `protobuf:"bytes,5,opt,name=dataAdmin,proto3" json:"dataAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminLoginResponse) Reset()         { *m = AdminLoginResponse{} }
func (m *AdminLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AdminLoginResponse) ProtoMessage()    {}
func (*AdminLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{1}
}

func (m *AdminLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminLoginResponse.Unmarshal(m, b)
}
func (m *AdminLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminLoginResponse.Marshal(b, m, deterministic)
}
func (m *AdminLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminLoginResponse.Merge(m, src)
}
func (m *AdminLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AdminLoginResponse.Size(m)
}
func (m *AdminLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminLoginResponse proto.InternalMessageInfo

func (m *AdminLoginResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminLoginResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdminLoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AdminLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AdminLoginResponse) GetDataAdmin() *DataAdmin {
	if m != nil {
		return m.DataAdmin
	}
	return nil
}

type AdminResetPasswordRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminResetPasswordRequest) Reset()         { *m = AdminResetPasswordRequest{} }
func (m *AdminResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AdminResetPasswordRequest) ProtoMessage()    {}
func (*AdminResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{2}
}

func (m *AdminResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminResetPasswordRequest.Unmarshal(m, b)
}
func (m *AdminResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *AdminResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminResetPasswordRequest.Merge(m, src)
}
func (m *AdminResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AdminResetPasswordRequest.Size(m)
}
func (m *AdminResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminResetPasswordRequest proto.InternalMessageInfo

func (m *AdminResetPasswordRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminResetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AdminResetPasswordRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AdminResetPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AdminChangePasswordRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	OldPassword          string   `protobuf:"bytes,2,opt,name=oldPassword,proto3" json:"oldPassword,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminChangePasswordRequest) Reset()         { *m = AdminChangePasswordRequest{} }
func (m *AdminChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AdminChangePasswordRequest) ProtoMessage()    {}
func (*AdminChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{3}
}

func (m *AdminChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminChangePasswordRequest.Unmarshal(m, b)
}
func (m *AdminChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *AdminChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminChangePasswordRequest.Merge(m, src)
}
func (m *AdminChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AdminChangePasswordRequest.Size(m)
}
func (m *AdminChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminChangePasswordRequest proto.InternalMessageInfo

func (m *AdminChangePasswordRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminChangePasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *AdminChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

//for customer
type CustomerLoginRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Pin                  string   `protobuf:"bytes,3,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerLoginRequest) Reset()         { *m = CustomerLoginRequest{} }
func (m *CustomerLoginRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerLoginRequest) ProtoMessage()    {}
func (*CustomerLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{4}
}

func (m *CustomerLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerLoginRequest.Unmarshal(m, b)
}
func (m *CustomerLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerLoginRequest.Marshal(b, m, deterministic)
}
func (m *CustomerLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerLoginRequest.Merge(m, src)
}
func (m *CustomerLoginRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerLoginRequest.Size(m)
}
func (m *CustomerLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerLoginRequest proto.InternalMessageInfo

func (m *CustomerLoginRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CustomerLoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerLoginRequest) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type CustomerLoginResponse struct {
	RequestId            string    `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Status               int32     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Token                string    `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	DataUser             *DataUser `protobuf:"bytes,5,opt,name=dataUser,proto3" json:"dataUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CustomerLoginResponse) Reset()         { *m = CustomerLoginResponse{} }
func (m *CustomerLoginResponse) String() string { return proto.CompactTextString(m) }
func (*CustomerLoginResponse) ProtoMessage()    {}
func (*CustomerLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{5}
}

func (m *CustomerLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerLoginResponse.Unmarshal(m, b)
}
func (m *CustomerLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerLoginResponse.Marshal(b, m, deterministic)
}
func (m *CustomerLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerLoginResponse.Merge(m, src)
}
func (m *CustomerLoginResponse) XXX_Size() int {
	return xxx_messageInfo_CustomerLoginResponse.Size(m)
}
func (m *CustomerLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerLoginResponse proto.InternalMessageInfo

func (m *CustomerLoginResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CustomerLoginResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CustomerLoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CustomerLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CustomerLoginResponse) GetDataUser() *DataUser {
	if m != nil {
		return m.DataUser
	}
	return nil
}

type CustomerVerifyOtpRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	OtpCode              string   `protobuf:"bytes,3,opt,name=otpCode,proto3" json:"otpCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerVerifyOtpRequest) Reset()         { *m = CustomerVerifyOtpRequest{} }
func (m *CustomerVerifyOtpRequest) String() string { return proto.CompactTextString(m) }
func (*CustomerVerifyOtpRequest) ProtoMessage()    {}
func (*CustomerVerifyOtpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{6}
}

func (m *CustomerVerifyOtpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerVerifyOtpRequest.Unmarshal(m, b)
}
func (m *CustomerVerifyOtpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerVerifyOtpRequest.Marshal(b, m, deterministic)
}
func (m *CustomerVerifyOtpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerVerifyOtpRequest.Merge(m, src)
}
func (m *CustomerVerifyOtpRequest) XXX_Size() int {
	return xxx_messageInfo_CustomerVerifyOtpRequest.Size(m)
}
func (m *CustomerVerifyOtpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerVerifyOtpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerVerifyOtpRequest proto.InternalMessageInfo

func (m *CustomerVerifyOtpRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *CustomerVerifyOtpRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CustomerVerifyOtpRequest) GetOtpCode() string {
	if m != nil {
		return m.OtpCode
	}
	return ""
}

//for agent
type AgentLoginRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Phone                string   `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	OtpCode              string   `protobuf:"bytes,3,opt,name=otpCode,proto3" json:"otpCode,omitempty"`
	ResCaptcha           string   `protobuf:"bytes,4,opt,name=resCaptcha,proto3" json:"resCaptcha,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentLoginRequest) Reset()         { *m = AgentLoginRequest{} }
func (m *AgentLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AgentLoginRequest) ProtoMessage()    {}
func (*AgentLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{7}
}

func (m *AgentLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentLoginRequest.Unmarshal(m, b)
}
func (m *AgentLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentLoginRequest.Marshal(b, m, deterministic)
}
func (m *AgentLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentLoginRequest.Merge(m, src)
}
func (m *AgentLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AgentLoginRequest.Size(m)
}
func (m *AgentLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentLoginRequest proto.InternalMessageInfo

func (m *AgentLoginRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AgentLoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *AgentLoginRequest) GetOtpCode() string {
	if m != nil {
		return m.OtpCode
	}
	return ""
}

func (m *AgentLoginRequest) GetResCaptcha() string {
	if m != nil {
		return m.ResCaptcha
	}
	return ""
}

type AgentLoginResponse struct {
	RequestId            string     `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Status               int32      `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Token                string     `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	DataAgent            *DataAgent `protobuf:"bytes,5,opt,name=dataAgent,proto3" json:"dataAgent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AgentLoginResponse) Reset()         { *m = AgentLoginResponse{} }
func (m *AgentLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AgentLoginResponse) ProtoMessage()    {}
func (*AgentLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{8}
}

func (m *AgentLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentLoginResponse.Unmarshal(m, b)
}
func (m *AgentLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentLoginResponse.Marshal(b, m, deterministic)
}
func (m *AgentLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentLoginResponse.Merge(m, src)
}
func (m *AgentLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AgentLoginResponse.Size(m)
}
func (m *AgentLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AgentLoginResponse proto.InternalMessageInfo

func (m *AgentLoginResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AgentLoginResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AgentLoginResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AgentLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AgentLoginResponse) GetDataAgent() *DataAgent {
	if m != nil {
		return m.DataAgent
	}
	return nil
}

type AgentLoginPartnerRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	OutletCode           string   `protobuf:"bytes,2,opt,name=outletCode,proto3" json:"outletCode,omitempty"`
	OutletName           string   `protobuf:"bytes,3,opt,name=outletName,proto3" json:"outletName,omitempty"`
	MerchantCode         string   `protobuf:"bytes,4,opt,name=merchantCode,proto3" json:"merchantCode,omitempty"`
	BranchCode           string   `protobuf:"bytes,5,opt,name=branchCode,proto3" json:"branchCode,omitempty"`
	RegionCode           string   `protobuf:"bytes,6,opt,name=regionCode,proto3" json:"regionCode,omitempty"`
	RegionName           string   `protobuf:"bytes,7,opt,name=regionName,proto3" json:"regionName,omitempty"`
	BranchName           string   `protobuf:"bytes,8,opt,name=branchName,proto3" json:"branchName,omitempty"`
	ZipCode              string   `protobuf:"bytes,9,opt,name=zipCode,proto3" json:"zipCode,omitempty"`
	PhoneNumber          string   `protobuf:"bytes,10,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Address              string   `protobuf:"bytes,11,opt,name=address,proto3" json:"address,omitempty"`
	Longitude            float32  `protobuf:"fixed32,12,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32  `protobuf:"fixed32,13,opt,name=latitude,proto3" json:"latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentLoginPartnerRequest) Reset()         { *m = AgentLoginPartnerRequest{} }
func (m *AgentLoginPartnerRequest) String() string { return proto.CompactTextString(m) }
func (*AgentLoginPartnerRequest) ProtoMessage()    {}
func (*AgentLoginPartnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{9}
}

func (m *AgentLoginPartnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentLoginPartnerRequest.Unmarshal(m, b)
}
func (m *AgentLoginPartnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentLoginPartnerRequest.Marshal(b, m, deterministic)
}
func (m *AgentLoginPartnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentLoginPartnerRequest.Merge(m, src)
}
func (m *AgentLoginPartnerRequest) XXX_Size() int {
	return xxx_messageInfo_AgentLoginPartnerRequest.Size(m)
}
func (m *AgentLoginPartnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentLoginPartnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AgentLoginPartnerRequest proto.InternalMessageInfo

func (m *AgentLoginPartnerRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetOutletCode() string {
	if m != nil {
		return m.OutletCode
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetOutletName() string {
	if m != nil {
		return m.OutletName
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetMerchantCode() string {
	if m != nil {
		return m.MerchantCode
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetBranchCode() string {
	if m != nil {
		return m.BranchCode
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetRegionCode() string {
	if m != nil {
		return m.RegionCode
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetRegionName() string {
	if m != nil {
		return m.RegionName
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetZipCode() string {
	if m != nil {
		return m.ZipCode
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AgentLoginPartnerRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *AgentLoginPartnerRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

//for all
type DefaultResponse struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultResponse) Reset()         { *m = DefaultResponse{} }
func (m *DefaultResponse) String() string { return proto.CompactTextString(m) }
func (*DefaultResponse) ProtoMessage()    {}
func (*DefaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{10}
}

func (m *DefaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultResponse.Unmarshal(m, b)
}
func (m *DefaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultResponse.Marshal(b, m, deterministic)
}
func (m *DefaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultResponse.Merge(m, src)
}
func (m *DefaultResponse) XXX_Size() int {
	return xxx_messageInfo_DefaultResponse.Size(m)
}
func (m *DefaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultResponse proto.InternalMessageInfo

func (m *DefaultResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *DefaultResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DefaultResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LogoutRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{11}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SessionRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionRequest) Reset()         { *m = SessionRequest{} }
func (m *SessionRequest) String() string { return proto.CompactTextString(m) }
func (*SessionRequest) ProtoMessage()    {}
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{12}
}

func (m *SessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionRequest.Unmarshal(m, b)
}
func (m *SessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionRequest.Marshal(b, m, deterministic)
}
func (m *SessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionRequest.Merge(m, src)
}
func (m *SessionRequest) XXX_Size() int {
	return xxx_messageInfo_SessionRequest.Size(m)
}
func (m *SessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SessionRequest proto.InternalMessageInfo

func (m *SessionRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SessionRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type SessionResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data                 *SessionData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	RequestId            string       `protobuf:"bytes,4,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SessionResponse) Reset()         { *m = SessionResponse{} }
func (m *SessionResponse) String() string { return proto.CompactTextString(m) }
func (*SessionResponse) ProtoMessage()    {}
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{13}
}

func (m *SessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionResponse.Unmarshal(m, b)
}
func (m *SessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionResponse.Marshal(b, m, deterministic)
}
func (m *SessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionResponse.Merge(m, src)
}
func (m *SessionResponse) XXX_Size() int {
	return xxx_messageInfo_SessionResponse.Size(m)
}
func (m *SessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SessionResponse proto.InternalMessageInfo

func (m *SessionResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SessionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SessionResponse) GetData() *SessionData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SessionResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type SessionData struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionData) Reset()         { *m = SessionData{} }
func (m *SessionData) String() string { return proto.CompactTextString(m) }
func (*SessionData) ProtoMessage()    {}
func (*SessionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{14}
}

func (m *SessionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionData.Unmarshal(m, b)
}
func (m *SessionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionData.Marshal(b, m, deterministic)
}
func (m *SessionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionData.Merge(m, src)
}
func (m *SessionData) XXX_Size() int {
	return xxx_messageInfo_SessionData.Size(m)
}
func (m *SessionData) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionData.DiscardUnknown(m)
}

var xxx_messageInfo_SessionData proto.InternalMessageInfo

func (m *SessionData) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SessionData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SessionData) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SessionData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SessionData) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type MailRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailRequest) Reset()         { *m = MailRequest{} }
func (m *MailRequest) String() string { return proto.CompactTextString(m) }
func (*MailRequest) ProtoMessage()    {}
func (*MailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{15}
}

func (m *MailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailRequest.Unmarshal(m, b)
}
func (m *MailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailRequest.Marshal(b, m, deterministic)
}
func (m *MailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailRequest.Merge(m, src)
}
func (m *MailRequest) XXX_Size() int {
	return xxx_messageInfo_MailRequest.Size(m)
}
func (m *MailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MailRequest proto.InternalMessageInfo

func (m *MailRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *MailRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *MailRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type MailResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string   `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MailResponse) Reset()         { *m = MailResponse{} }
func (m *MailResponse) String() string { return proto.CompactTextString(m) }
func (*MailResponse) ProtoMessage()    {}
func (*MailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{16}
}

func (m *MailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MailResponse.Unmarshal(m, b)
}
func (m *MailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MailResponse.Marshal(b, m, deterministic)
}
func (m *MailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MailResponse.Merge(m, src)
}
func (m *MailResponse) XXX_Size() int {
	return xxx_messageInfo_MailResponse.Size(m)
}
func (m *MailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MailResponse proto.InternalMessageInfo

func (m *MailResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MailResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

type SmsRequest struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsRequest) Reset()         { *m = SmsRequest{} }
func (m *SmsRequest) String() string { return proto.CompactTextString(m) }
func (*SmsRequest) ProtoMessage()    {}
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{17}
}

func (m *SmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsRequest.Unmarshal(m, b)
}
func (m *SmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsRequest.Marshal(b, m, deterministic)
}
func (m *SmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsRequest.Merge(m, src)
}
func (m *SmsRequest) XXX_Size() int {
	return xxx_messageInfo_SmsRequest.Size(m)
}
func (m *SmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsRequest proto.InternalMessageInfo

func (m *SmsRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *SmsRequest) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *SmsRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SmsResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string   `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsResponse) Reset()         { *m = SmsResponse{} }
func (m *SmsResponse) String() string { return proto.CompactTextString(m) }
func (*SmsResponse) ProtoMessage()    {}
func (*SmsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9d38a2cdbb4f144, []int{18}
}

func (m *SmsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsResponse.Unmarshal(m, b)
}
func (m *SmsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsResponse.Marshal(b, m, deterministic)
}
func (m *SmsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsResponse.Merge(m, src)
}
func (m *SmsResponse) XXX_Size() int {
	return xxx_messageInfo_SmsResponse.Size(m)
}
func (m *SmsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsResponse proto.InternalMessageInfo

func (m *SmsResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *SmsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SmsResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func init() {
	proto.RegisterType((*AdminLoginRequest)(nil), "proto.AdminLoginRequest")
	proto.RegisterType((*AdminLoginResponse)(nil), "proto.AdminLoginResponse")
	proto.RegisterType((*AdminResetPasswordRequest)(nil), "proto.AdminResetPasswordRequest")
	proto.RegisterType((*AdminChangePasswordRequest)(nil), "proto.AdminChangePasswordRequest")
	proto.RegisterType((*CustomerLoginRequest)(nil), "proto.CustomerLoginRequest")
	proto.RegisterType((*CustomerLoginResponse)(nil), "proto.CustomerLoginResponse")
	proto.RegisterType((*CustomerVerifyOtpRequest)(nil), "proto.CustomerVerifyOtpRequest")
	proto.RegisterType((*AgentLoginRequest)(nil), "proto.AgentLoginRequest")
	proto.RegisterType((*AgentLoginResponse)(nil), "proto.AgentLoginResponse")
	proto.RegisterType((*AgentLoginPartnerRequest)(nil), "proto.AgentLoginPartnerRequest")
	proto.RegisterType((*DefaultResponse)(nil), "proto.DefaultResponse")
	proto.RegisterType((*LogoutRequest)(nil), "proto.LogoutRequest")
	proto.RegisterType((*SessionRequest)(nil), "proto.SessionRequest")
	proto.RegisterType((*SessionResponse)(nil), "proto.SessionResponse")
	proto.RegisterType((*SessionData)(nil), "proto.SessionData")
	proto.RegisterType((*MailRequest)(nil), "proto.MailRequest")
	proto.RegisterType((*MailResponse)(nil), "proto.MailResponse")
	proto.RegisterType((*SmsRequest)(nil), "proto.SmsRequest")
	proto.RegisterType((*SmsResponse)(nil), "proto.SmsResponse")
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor_a9d38a2cdbb4f144) }

var fileDescriptor_a9d38a2cdbb4f144 = []byte{
	// 1167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0xae, 0x1d, 0x27, 0x8e, 0xc7, 0x79, 0xdd, 0x24, 0xed, 0xc5, 0x44, 0x6d, 0xb8, 0x0f, 0x28,
	0x12, 0x6a, 0x82, 0x82, 0xc4, 0x37, 0xa4, 0x06, 0x07, 0x4a, 0x51, 0x28, 0x91, 0x23, 0x2a, 0x84,
	0x28, 0x62, 0xed, 0xdb, 0xfa, 0x0e, 0xee, 0x76, 0xcd, 0xee, 0x5e, 0x4b, 0x91, 0x00, 0x21, 0x3e,
	0xf1, 0x57, 0x10, 0x7f, 0x85, 0xff, 0x84, 0xf6, 0xed, 0x6e, 0xcf, 0x71, 0x9d, 0xd4, 0x4e, 0xe1,
	0xd3, 0xed, 0x3e, 0x33, 0xfb, 0xec, 0x33, 0xb3, 0xb3, 0x77, 0x73, 0xb0, 0x31, 0xe2, 0x4c, 0xb2,
	0x23, 0x9c, 0xcb, 0xf8, 0x50, 0x0f, 0xd1, 0xa2, 0x7e, 0x74, 0x76, 0x8c, 0x21, 0xc2, 0x22, 0xee,
	0x33, 0xcc, 0x23, 0x63, 0xed, 0x58, 0xff, 0x5c, 0x10, 0x6e, 0x91, 0x4d, 0xcb, 0x30, 0x24, 0x54,
	0x1a, 0x28, 0xfc, 0xa3, 0x06, 0x9b, 0x27, 0x51, 0x96, 0xd0, 0x33, 0x36, 0x4c, 0x68, 0x8f, 0xfc,
	0x98, 0x13, 0x21, 0xd1, 0x1e, 0xb4, 0xb8, 0x19, 0x3e, 0x8a, 0x82, 0xda, 0x7e, 0xed, 0xa0, 0xd5,
	0x2b, 0x01, 0xb4, 0x0d, 0x8b, 0x24, 0xc3, 0x49, 0x1a, 0xd4, 0xb5, 0xc5, 0x4c, 0x50, 0x07, 0x96,
	0x47, 0x58, 0x88, 0x17, 0x8c, 0x47, 0xc1, 0x82, 0x36, 0x14, 0x73, 0x74, 0x17, 0x80, 0x13, 0xd1,
	0xc5, 0x23, 0x39, 0x88, 0x71, 0xd0, 0xd0, 0x56, 0x0f, 0x09, 0xff, 0xaa, 0x01, 0xf2, 0x55, 0x88,
	0x11, 0xa3, 0x82, 0x5c, 0x21, 0xe3, 0x36, 0x2c, 0x09, 0x89, 0x65, 0x2e, 0xb4, 0x8e, 0xc5, 0x9e,
	0x9d, 0xa1, 0x00, 0x9a, 0x19, 0x11, 0x02, 0x0f, 0x89, 0xd5, 0xe1, 0xa6, 0x4a, 0xb8, 0x64, 0x3f,
	0x10, 0x6a, 0x15, 0x98, 0x09, 0x3a, 0x84, 0x56, 0x84, 0x25, 0xd6, 0xfb, 0x07, 0x8b, 0xfb, 0xb5,
	0x83, 0xf6, 0xf1, 0x86, 0xc9, 0xce, 0xe1, 0xa9, 0xc3, 0x7b, 0xa5, 0x4b, 0xf8, 0x1b, 0xec, 0x1a,
	0x8c, 0x08, 0x22, 0xcf, 0x6d, 0x88, 0xf3, 0x64, 0x0e, 0x41, 0x63, 0xc0, 0x22, 0xa7, 0x56, 0x8f,
	0x2b, 0xd9, 0x6c, 0x54, 0xb3, 0x19, 0xfe, 0x0a, 0x1d, 0x2d, 0xa0, 0x1b, 0x63, 0x3a, 0x24, 0xaf,
	0xa7, 0x60, 0x1f, 0xda, 0x2c, 0x8d, 0xdc, 0x1a, 0xab, 0xc3, 0x87, 0x94, 0x07, 0x25, 0x2f, 0xce,
	0xab, 0x47, 0xe9, 0x43, 0xe1, 0x37, 0xb0, 0xdd, 0xcd, 0x85, 0x64, 0x19, 0xe1, 0xaf, 0x57, 0x35,
	0xa3, 0x98, 0x51, 0xe2, 0x62, 0xd7, 0x13, 0xb4, 0x01, 0x0b, 0xa3, 0x84, 0xda, 0x5d, 0xd4, 0x50,
	0xd5, 0xc2, 0xce, 0x18, 0xfd, 0x7f, 0x5a, 0x0e, 0xef, 0xc2, 0xb2, 0x3a, 0xeb, 0x2f, 0x05, 0xe1,
	0xb6, 0x1a, 0xd6, 0xbd, 0x6a, 0x50, 0x70, 0xaf, 0x70, 0x08, 0x63, 0x08, 0x9c, 0xd6, 0x27, 0x84,
	0x27, 0xcf, 0x5e, 0x7e, 0x21, 0x47, 0xf3, 0xa4, 0x23, 0x80, 0x26, 0x93, 0xa3, 0x6e, 0x59, 0x0d,
	0x6e, 0x1a, 0xfe, 0xae, 0x2e, 0xaa, 0xba, 0xb8, 0x73, 0xa7, 0xfc, 0x95, 0x7b, 0x5c, 0xef, 0x9a,
	0x7a, 0x1a, 0xfe, 0x97, 0x6b, 0xaa, 0xf6, 0x9f, 0x74, 0x4d, 0x15, 0xde, 0x2b, 0x5d, 0xc2, 0xbf,
	0x17, 0x20, 0x28, 0xc5, 0x9e, 0x63, 0x2e, 0x29, 0xe1, 0xd7, 0xcb, 0xdb, 0x5d, 0x00, 0x96, 0xcb,
	0x94, 0x48, 0x9d, 0x24, 0x93, 0x3c, 0x0f, 0x29, 0xed, 0x8f, 0x71, 0xe6, 0xd4, 0x7b, 0x08, 0x0a,
	0x61, 0x25, 0x23, 0x7c, 0x10, 0x63, 0x6a, 0x18, 0x4c, 0x1c, 0x15, 0x4c, 0x71, 0xf4, 0x39, 0xa6,
	0x83, 0x58, 0x7b, 0x2c, 0x1a, 0x8e, 0x12, 0x31, 0x67, 0x31, 0x4c, 0x18, 0xd5, 0xf6, 0x25, 0x77,
	0x16, 0x0e, 0x29, 0xed, 0x5a, 0x43, 0xd3, 0xb7, 0x6b, 0x0d, 0x05, 0xbf, 0xb6, 0x2f, 0xfb, 0xfc,
	0xda, 0x1e, 0x40, 0xf3, 0xe7, 0xc4, 0x54, 0x41, 0xcb, 0xa4, 0xdf, 0x4e, 0xd5, 0x0b, 0x40, 0x17,
	0xca, 0xe3, 0x3c, 0xeb, 0x13, 0x1e, 0x80, 0x79, 0x01, 0x78, 0x90, 0x5a, 0x8b, 0xa3, 0x88, 0x13,
	0x21, 0x82, 0xb6, 0x59, 0x6b, 0xa7, 0x2a, 0xaf, 0x29, 0xa3, 0xc3, 0x44, 0xe6, 0x11, 0x09, 0x56,
	0xf6, 0x6b, 0x07, 0xf5, 0x5e, 0x09, 0xa8, 0x97, 0x5a, 0x8a, 0xa5, 0x31, 0xae, 0x6a, 0x63, 0x31,
	0x0f, 0x31, 0xac, 0x9f, 0x92, 0x67, 0x38, 0x4f, 0xe5, 0x9b, 0xaa, 0xab, 0xb0, 0x0b, 0xab, 0x67,
	0x6c, 0xc8, 0x72, 0x79, 0xed, 0xdb, 0x63, 0xca, 0xb0, 0xee, 0x95, 0x61, 0x78, 0x0a, 0x6b, 0x17,
	0x44, 0x88, 0x84, 0x15, 0x77, 0xb0, 0xf0, 0xab, 0xf9, 0xe5, 0xba, 0x07, 0x2d, 0x91, 0x0c, 0x29,
	0x96, 0x39, 0x77, 0x25, 0x54, 0x02, 0xe1, 0x9f, 0x35, 0x58, 0x2f, 0x68, 0x6c, 0xb8, 0x65, 0x40,
	0xb5, 0x57, 0x05, 0x54, 0xaf, 0x5e, 0x94, 0x77, 0xa0, 0xa1, 0xea, 0x5d, 0xc7, 0xd9, 0x3e, 0x46,
	0xf6, 0x36, 0x58, 0x5e, 0x75, 0x29, 0x7a, 0xda, 0x5e, 0x8d, 0xb3, 0x31, 0x16, 0x67, 0xf8, 0x0b,
	0xb4, 0xbd, 0x25, 0xea, 0x90, 0x54, 0xcb, 0x40, 0x55, 0xd9, 0x98, 0x88, 0x8a, 0xb9, 0xfa, 0x52,
	0x69, 0xdc, 0xe8, 0x68, 0x38, 0x4c, 0xbe, 0x1c, 0x15, 0x5f, 0x2f, 0x35, 0x56, 0xa1, 0xa8, 0x35,
	0xc5, 0x6e, 0x76, 0xa6, 0x7c, 0x39, 0x4b, 0x5d, 0xb9, 0xeb, 0x71, 0x98, 0x40, 0xfb, 0x73, 0x9c,
	0xa4, 0xd7, 0x3b, 0x13, 0xb7, 0x59, 0xdd, 0xdb, 0x2c, 0x80, 0xa6, 0xc8, 0xfb, 0xdf, 0x93, 0x81,
	0x74, 0x07, 0x6e, 0xa7, 0x68, 0x0d, 0xea, 0x92, 0x59, 0x09, 0x75, 0xc9, 0xc2, 0x6f, 0x61, 0xc5,
	0x6c, 0x35, 0x73, 0xc6, 0x2b, 0xea, 0x16, 0xc6, 0x33, 0xf9, 0x1d, 0xc0, 0x45, 0x26, 0xae, 0xfd,
	0x21, 0x8e, 0x88, 0x90, 0x09, 0xc5, 0x32, 0x61, 0xee, 0x03, 0xe8, 0x43, 0x3a, 0x56, 0xf2, 0x93,
	0xb4, 0xfa, 0xf5, 0x38, 0x7c, 0x0a, 0x6d, 0xbd, 0xc3, 0x9b, 0x09, 0xe0, 0xf8, 0x9f, 0x35, 0x68,
	0x9f, 0xe4, 0x32, 0xbe, 0x20, 0xfc, 0x79, 0x32, 0x20, 0xe8, 0x04, 0xd6, 0x1e, 0x12, 0xa9, 0xca,
	0xc2, 0x56, 0x08, 0xda, 0xa9, 0x16, 0x99, 0x8d, 0xb5, 0x73, 0x7b, 0x1c, 0x36, 0x02, 0xc3, 0x5b,
	0xe8, 0x18, 0x9a, 0x17, 0x84, 0x46, 0x17, 0x99, 0x40, 0x9b, 0xce, 0xa9, 0xc8, 0x51, 0x07, 0xf9,
	0x50, 0xb1, 0xe6, 0x03, 0x68, 0xa9, 0x35, 0x1f, 0x9b, 0xee, 0xc8, 0xba, 0x78, 0x45, 0xd2, 0xd9,
	0xaa, 0x60, 0xc5, 0xba, 0x87, 0xb0, 0xad, 0x1b, 0xa3, 0x27, 0x38, 0x4d, 0x22, 0x2c, 0xc9, 0xcc,
	0xa2, 0xbb, 0x00, 0x65, 0x3b, 0x8a, 0x02, 0xeb, 0x77, 0xa9, 0x4f, 0xee, 0xec, 0x4e, 0xb0, 0x14,
	0x24, 0x9f, 0xfa, 0x3d, 0xad, 0x93, 0x34, 0x85, 0xcc, 0xc9, 0x19, 0x7b, 0x0d, 0x86, 0xb7, 0xd0,
	0x23, 0xd8, 0xd2, 0xee, 0x9f, 0x30, 0x3e, 0x64, 0x45, 0xcb, 0x39, 0x13, 0xd5, 0xb9, 0x15, 0x55,
	0x69, 0x5e, 0xd1, 0xbe, 0xcf, 0x34, 0xa9, 0xaf, 0x9d, 0xc2, 0xf8, 0x95, 0xed, 0x46, 0x2b, 0xcb,
	0x8a, 0x70, 0xe7, 0x61, 0xee, 0xd9, 0xb0, 0xab, 0x7d, 0x2e, 0x7a, 0xdb, 0xa7, 0x9c, 0xd8, 0x03,
	0x4f, 0xe1, 0xfc, 0x10, 0xda, 0x2e, 0x5d, 0x2c, 0x97, 0x68, 0xdb, 0x3a, 0x56, 0xbe, 0x0b, 0x53,
	0x96, 0x7f, 0x06, 0x77, 0x8a, 0x7e, 0x6f, 0xde, 0x22, 0x3b, 0x83, 0xd5, 0x4a, 0x9f, 0x8b, 0xde,
	0xb2, 0xae, 0x93, 0x9a, 0xeb, 0xce, 0xde, 0x64, 0xa3, 0x77, 0xb0, 0x9b, 0xce, 0xd4, 0xe5, 0x04,
	0x4b, 0x72, 0x7e, 0x83, 0x8c, 0xa6, 0xb7, 0xbd, 0x01, 0xc6, 0x3b, 0x55, 0x46, 0x7b, 0x7a, 0x57,
	0xf1, 0x4e, 0x3b, 0x8f, 0x32, 0xea, 0x1b, 0xe4, 0xb2, 0x17, 0x6d, 0x76, 0xae, 0xa7, 0xd0, 0xb9,
	0xf4, 0x5f, 0x50, 0x92, 0xde, 0x1b, 0x23, 0x1d, 0xff, 0x75, 0xb8, 0x32, 0x91, 0x0f, 0x60, 0xcd,
	0x33, 0xcd, 0x52, 0xc8, 0xea, 0x55, 0xa9, 0x9a, 0xe3, 0xb9, 0xab, 0xf8, 0x01, 0x40, 0xd9, 0x65,
	0x97, 0xaf, 0xa4, 0xf1, 0x3f, 0x95, 0x29, 0x52, 0xce, 0x60, 0xcb, 0x48, 0x71, 0x59, 0xb8, 0x8a,
	0x6a, 0x77, 0x82, 0xa5, 0x72, 0xc1, 0x2d, 0x3e, 0x4b, 0x5e, 0xce, 0x60, 0xc5, 0xfe, 0x2a, 0x18,
	0x15, 0xf7, 0x2e, 0xed, 0x55, 0xfd, 0x93, 0x98, 0x2a, 0xe6, 0xa3, 0xf7, 0xbe, 0x3e, 0x1c, 0x26,
	0x32, 0xce, 0xfb, 0x87, 0x03, 0x96, 0x1d, 0x45, 0xe4, 0x39, 0xce, 0xfa, 0x49, 0x9a, 0xd0, 0xa3,
	0x3e, 0x8b, 0xee, 0xdb, 0xf1, 0xfd, 0x01, 0xcb, 0x32, 0x46, 0x8f, 0x34, 0x4d, 0x7f, 0x49, 0x3f,
	0xde, 0xff, 0x37, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x64, 0xb7, 0xe6, 0xed, 0x11, 0x00, 0x00,
}
