// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dashboard.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MasterConfigRequest struct {
	RequestId            string            `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string            `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	MasterConfig         *DataMasterConfig `protobuf:"bytes,3,opt,name=masterConfig,proto3" json:"masterConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MasterConfigRequest) Reset()         { *m = MasterConfigRequest{} }
func (m *MasterConfigRequest) String() string { return proto.CompactTextString(m) }
func (*MasterConfigRequest) ProtoMessage()    {}
func (*MasterConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0d714c6f8e139fe, []int{0}
}

func (m *MasterConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterConfigRequest.Unmarshal(m, b)
}
func (m *MasterConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterConfigRequest.Marshal(b, m, deterministic)
}
func (m *MasterConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterConfigRequest.Merge(m, src)
}
func (m *MasterConfigRequest) XXX_Size() int {
	return xxx_messageInfo_MasterConfigRequest.Size(m)
}
func (m *MasterConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterConfigRequest proto.InternalMessageInfo

func (m *MasterConfigRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *MasterConfigRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *MasterConfigRequest) GetMasterConfig() *DataMasterConfig {
	if m != nil {
		return m.MasterConfig
	}
	return nil
}

type MasterConfigResponse struct {
	Status               int32               `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string              `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string              `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	DataMasterConfig     *DataMasterConfig   `protobuf:"bytes,5,opt,name=dataMasterConfig,proto3" json:"dataMasterConfig,omitempty"`
	ListMasterConfig     []*DataMasterConfig `protobuf:"bytes,6,rep,name=listMasterConfig,proto3" json:"listMasterConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MasterConfigResponse) Reset()         { *m = MasterConfigResponse{} }
func (m *MasterConfigResponse) String() string { return proto.CompactTextString(m) }
func (*MasterConfigResponse) ProtoMessage()    {}
func (*MasterConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0d714c6f8e139fe, []int{1}
}

func (m *MasterConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterConfigResponse.Unmarshal(m, b)
}
func (m *MasterConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterConfigResponse.Marshal(b, m, deterministic)
}
func (m *MasterConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterConfigResponse.Merge(m, src)
}
func (m *MasterConfigResponse) XXX_Size() int {
	return xxx_messageInfo_MasterConfigResponse.Size(m)
}
func (m *MasterConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasterConfigResponse proto.InternalMessageInfo

func (m *MasterConfigResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MasterConfigResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MasterConfigResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *MasterConfigResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *MasterConfigResponse) GetDataMasterConfig() *DataMasterConfig {
	if m != nil {
		return m.DataMasterConfig
	}
	return nil
}

func (m *MasterConfigResponse) GetListMasterConfig() []*DataMasterConfig {
	if m != nil {
		return m.ListMasterConfig
	}
	return nil
}

type DataMasterConfig struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParamKey             string   `protobuf:"bytes,2,opt,name=paramKey,proto3" json:"paramKey,omitempty"`
	ParamValue           string   `protobuf:"bytes,3,opt,name=paramValue,proto3" json:"paramValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMasterConfig) Reset()         { *m = DataMasterConfig{} }
func (m *DataMasterConfig) String() string { return proto.CompactTextString(m) }
func (*DataMasterConfig) ProtoMessage()    {}
func (*DataMasterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0d714c6f8e139fe, []int{2}
}

func (m *DataMasterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataMasterConfig.Unmarshal(m, b)
}
func (m *DataMasterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataMasterConfig.Marshal(b, m, deterministic)
}
func (m *DataMasterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMasterConfig.Merge(m, src)
}
func (m *DataMasterConfig) XXX_Size() int {
	return xxx_messageInfo_DataMasterConfig.Size(m)
}
func (m *DataMasterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMasterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DataMasterConfig proto.InternalMessageInfo

func (m *DataMasterConfig) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DataMasterConfig) GetParamKey() string {
	if m != nil {
		return m.ParamKey
	}
	return ""
}

func (m *DataMasterConfig) GetParamValue() string {
	if m != nil {
		return m.ParamValue
	}
	return ""
}

type AdminRequest struct {
	RequestId            string     `protobuf:"bytes,1,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string     `protobuf:"bytes,2,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	Admin                *DataAdmin `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminRequest) Reset()         { *m = AdminRequest{} }
func (m *AdminRequest) String() string { return proto.CompactTextString(m) }
func (*AdminRequest) ProtoMessage()    {}
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0d714c6f8e139fe, []int{3}
}

func (m *AdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminRequest.Unmarshal(m, b)
}
func (m *AdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminRequest.Marshal(b, m, deterministic)
}
func (m *AdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminRequest.Merge(m, src)
}
func (m *AdminRequest) XXX_Size() int {
	return xxx_messageInfo_AdminRequest.Size(m)
}
func (m *AdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminRequest proto.InternalMessageInfo

func (m *AdminRequest) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminRequest) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *AdminRequest) GetAdmin() *DataAdmin {
	if m != nil {
		return m.Admin
	}
	return nil
}

type AdminResponse struct {
	Status               int32        `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message              string       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RequestId            string       `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	RequestByService     string       `protobuf:"bytes,4,opt,name=requestByService,proto3" json:"requestByService,omitempty"`
	DataAdmin            *DataAdmin   `protobuf:"bytes,5,opt,name=dataAdmin,proto3" json:"dataAdmin,omitempty"`
	ListAdmin            []*DataAdmin `protobuf:"bytes,6,rep,name=listAdmin,proto3" json:"listAdmin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminResponse) Reset()         { *m = AdminResponse{} }
func (m *AdminResponse) String() string { return proto.CompactTextString(m) }
func (*AdminResponse) ProtoMessage()    {}
func (*AdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0d714c6f8e139fe, []int{4}
}

func (m *AdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminResponse.Unmarshal(m, b)
}
func (m *AdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminResponse.Marshal(b, m, deterministic)
}
func (m *AdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminResponse.Merge(m, src)
}
func (m *AdminResponse) XXX_Size() int {
	return xxx_messageInfo_AdminResponse.Size(m)
}
func (m *AdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminResponse proto.InternalMessageInfo

func (m *AdminResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AdminResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *AdminResponse) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *AdminResponse) GetRequestByService() string {
	if m != nil {
		return m.RequestByService
	}
	return ""
}

func (m *AdminResponse) GetDataAdmin() *DataAdmin {
	if m != nil {
		return m.DataAdmin
	}
	return nil
}

func (m *AdminResponse) GetListAdmin() []*DataAdmin {
	if m != nil {
		return m.ListAdmin
	}
	return nil
}

type DataAdmin struct {
	Created              int64    `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	Removed              int64    `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	CreatedBy            string   `protobuf:"bytes,4,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	UpdatedBy            string   `protobuf:"bytes,5,opt,name=updatedBy,proto3" json:"updatedBy,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,7,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Address              string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Email                string   `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,11,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,12,opt,name=phone,proto3" json:"phone,omitempty"`
	PhotoUrl             string   `protobuf:"bytes,13,opt,name=photoUrl,proto3" json:"photoUrl,omitempty"`
	AccessId             string   `protobuf:"bytes,14,opt,name=accessId,proto3" json:"accessId,omitempty"`
	ResetCode            string   `protobuf:"bytes,15,opt,name=resetCode,proto3" json:"resetCode,omitempty"`
	ResetExpiredTime     int64    `protobuf:"varint,16,opt,name=resetExpiredTime,proto3" json:"resetExpiredTime,omitempty"`
	IdOfficeRegional     int32    `protobuf:"varint,17,opt,name=idOfficeRegional,proto3" json:"idOfficeRegional,omitempty"`
	PersonalNumber       string   `protobuf:"bytes,18,opt,name=personalNumber,proto3" json:"personalNumber,omitempty"`
	IsSuperAdmin         bool     `protobuf:"varint,19,opt,name=isSuperAdmin,proto3" json:"isSuperAdmin,omitempty"`
	Role                 string   `protobuf:"bytes,20,opt,name=role,proto3" json:"role,omitempty"`
	RoleId               int32    `protobuf:"varint,21,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataAdmin) Reset()         { *m = DataAdmin{} }
func (m *DataAdmin) String() string { return proto.CompactTextString(m) }
func (*DataAdmin) ProtoMessage()    {}
func (*DataAdmin) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0d714c6f8e139fe, []int{5}
}

func (m *DataAdmin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataAdmin.Unmarshal(m, b)
}
func (m *DataAdmin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataAdmin.Marshal(b, m, deterministic)
}
func (m *DataAdmin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataAdmin.Merge(m, src)
}
func (m *DataAdmin) XXX_Size() int {
	return xxx_messageInfo_DataAdmin.Size(m)
}
func (m *DataAdmin) XXX_DiscardUnknown() {
	xxx_messageInfo_DataAdmin.DiscardUnknown(m)
}

var xxx_messageInfo_DataAdmin proto.InternalMessageInfo

func (m *DataAdmin) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *DataAdmin) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *DataAdmin) GetRemoved() int64 {
	if m != nil {
		return m.Removed
	}
	return 0
}

func (m *DataAdmin) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *DataAdmin) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *DataAdmin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DataAdmin) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DataAdmin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DataAdmin) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DataAdmin) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *DataAdmin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DataAdmin) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *DataAdmin) GetPhotoUrl() string {
	if m != nil {
		return m.PhotoUrl
	}
	return ""
}

func (m *DataAdmin) GetAccessId() string {
	if m != nil {
		return m.AccessId
	}
	return ""
}

func (m *DataAdmin) GetResetCode() string {
	if m != nil {
		return m.ResetCode
	}
	return ""
}

func (m *DataAdmin) GetResetExpiredTime() int64 {
	if m != nil {
		return m.ResetExpiredTime
	}
	return 0
}

func (m *DataAdmin) GetIdOfficeRegional() int32 {
	if m != nil {
		return m.IdOfficeRegional
	}
	return 0
}

func (m *DataAdmin) GetPersonalNumber() string {
	if m != nil {
		return m.PersonalNumber
	}
	return ""
}

func (m *DataAdmin) GetIsSuperAdmin() bool {
	if m != nil {
		return m.IsSuperAdmin
	}
	return false
}

func (m *DataAdmin) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *DataAdmin) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func init() {
	proto.RegisterType((*MasterConfigRequest)(nil), "proto.MasterConfigRequest")
	proto.RegisterType((*MasterConfigResponse)(nil), "proto.MasterConfigResponse")
	proto.RegisterType((*DataMasterConfig)(nil), "proto.DataMasterConfig")
	proto.RegisterType((*AdminRequest)(nil), "proto.AdminRequest")
	proto.RegisterType((*AdminResponse)(nil), "proto.AdminResponse")
	proto.RegisterType((*DataAdmin)(nil), "proto.DataAdmin")
}

func init() { proto.RegisterFile("proto/dashboard.proto", fileDescriptor_f0d714c6f8e139fe) }

var fileDescriptor_f0d714c6f8e139fe = []byte{
	// 1000 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x95, 0x5b, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0x71, 0x6e, 0x8d, 0x4f, 0x6e, 0xee, 0x38, 0x2d, 0xab, 0x80, 0x50, 0xe4, 0x87, 0x2a,
	0x42, 0x6a, 0x82, 0xca, 0x43, 0x4a, 0x0b, 0xb4, 0x71, 0x12, 0x42, 0x44, 0x4b, 0x23, 0xa7, 0xe1,
	0x81, 0x07, 0xa4, 0xf1, 0xce, 0x89, 0x3d, 0x62, 0x77, 0x67, 0x99, 0x99, 0x75, 0xeb, 0x37, 0x3e,
	0x48, 0xbf, 0x17, 0xe2, 0x33, 0xf0, 0x25, 0xd0, 0x5c, 0xd6, 0xf6, 0xc6, 0xa1, 0x62, 0x16, 0x1e,
	0xfa, 0xb4, 0x7b, 0x2e, 0xbf, 0xb9, 0x9d, 0xff, 0x99, 0x81, 0x7b, 0xb9, 0x14, 0x5a, 0x1c, 0x30,
	0xaa, 0x86, 0x7d, 0x41, 0x25, 0xdb, 0xb7, 0x36, 0x59, 0xb6, 0x9f, 0x9d, 0x96, 0x8b, 0xf6, 0xa9,
	0x42, 0x17, 0xe8, 0xbc, 0x6b, 0x40, 0xfb, 0x25, 0x55, 0x1a, 0xe5, 0xb1, 0xc8, 0xae, 0xf9, 0xa0,
	0x87, 0xbf, 0x15, 0xa8, 0x34, 0xf9, 0x14, 0x9a, 0xd2, 0xfd, 0x9e, 0xb3, 0xa8, 0xb1, 0xdb, 0xd8,
	0x6b, 0xf6, 0xa6, 0x0e, 0xf2, 0x39, 0xb4, 0xbc, 0xd1, 0x1d, 0x5f, 0xa2, 0x1c, 0xf1, 0x18, 0xa3,
	0x05, 0x9b, 0x34, 0xe7, 0x27, 0x4f, 0x61, 0x3d, 0x9d, 0x99, 0x20, 0x5a, 0xdc, 0x6d, 0xec, 0xad,
	0x3d, 0xfa, 0xd8, 0xcd, 0xbf, 0x7f, 0x42, 0x35, 0xad, 0xcc, 0x5f, 0x49, 0xee, 0xbc, 0x5b, 0x80,
	0xed, 0xea, 0xf2, 0x54, 0x2e, 0x32, 0x85, 0xe4, 0x3e, 0xac, 0x28, 0x4d, 0x75, 0xa1, 0xec, 0xe2,
	0x96, 0x7b, 0xde, 0x22, 0x11, 0xdc, 0x49, 0x51, 0x29, 0x3a, 0x28, 0x17, 0x54, 0x9a, 0xd5, 0x1d,
	0x2d, 0xfe, 0x9b, 0x1d, 0x2d, 0xfd, 0xc3, 0x8e, 0x8e, 0xa1, 0xc5, 0x6e, 0x2c, 0x3b, 0x5a, 0x7e,
	0xff, 0xae, 0xe6, 0x00, 0x33, 0x48, 0xc2, 0x95, 0xae, 0x0c, 0xb2, 0xb2, 0xbb, 0xf8, 0xde, 0x41,
	0x6e, 0x02, 0x9d, 0x5f, 0xa0, 0x75, 0x33, 0x8b, 0x6c, 0xc2, 0x02, 0x67, 0xfe, 0x54, 0x16, 0x38,
	0x23, 0x3b, 0xb0, 0x9a, 0x53, 0x49, 0xd3, 0x1f, 0x70, 0xec, 0x8f, 0x64, 0x62, 0x93, 0xcf, 0x00,
	0xec, 0xff, 0x4f, 0x34, 0x29, 0xd0, 0x1f, 0xca, 0x8c, 0xa7, 0xf3, 0x7b, 0x03, 0xd6, 0x8f, 0x58,
	0xca, 0xb3, 0xff, 0x5f, 0x16, 0x0f, 0x60, 0x99, 0x9a, 0x91, 0xbd, 0x1e, 0x5a, 0x33, 0x9b, 0x76,
	0x33, 0xba, 0x70, 0xe7, 0xaf, 0x06, 0x6c, 0xf8, 0x25, 0x7c, 0x00, 0xa5, 0xdf, 0x87, 0x26, 0x2b,
	0x57, 0xe8, 0x6b, 0x3e, 0xbf, 0xf2, 0x69, 0x8a, 0xc9, 0x37, 0x45, 0x73, 0xf9, 0xae, 0xbc, 0xb7,
	0xe4, 0x4f, 0x52, 0x3a, 0x7f, 0x2e, 0x41, 0x73, 0x12, 0x30, 0x3b, 0x8a, 0x25, 0x52, 0x8d, 0xee,
	0xac, 0x17, 0x7b, 0xa5, 0x69, 0x22, 0x45, 0xce, 0x6c, 0x64, 0xc1, 0x45, 0xbc, 0x69, 0x22, 0x12,
	0x53, 0x31, 0x42, 0xb7, 0xd3, 0xc5, 0x5e, 0x69, 0x9a, 0x53, 0xf0, 0x78, 0x77, 0xec, 0x37, 0x38,
	0x75, 0x98, 0xa8, 0x1f, 0xa2, 0x3b, 0xb6, 0x3b, 0x6b, 0xf6, 0xa6, 0x0e, 0x2f, 0xaa, 0x15, 0xeb,
	0x36, 0xa2, 0xba, 0x0f, 0x2b, 0x85, 0x42, 0x79, 0xce, 0xa2, 0x3b, 0xd6, 0xe7, 0x2d, 0x42, 0x60,
	0x29, 0xa3, 0x29, 0x46, 0xab, 0xd6, 0x6b, 0xff, 0xcd, 0x8a, 0x28, 0x63, 0x12, 0x95, 0x8a, 0x9a,
	0xae, 0x2e, 0xde, 0x24, 0xdb, 0xb0, 0x8c, 0x29, 0xe5, 0x49, 0x04, 0xd6, 0xef, 0x0c, 0x27, 0x58,
	0xa5, 0xde, 0x08, 0xc9, 0xa2, 0xb5, 0x52, 0xb0, 0xce, 0x36, 0x44, 0x3e, 0x14, 0x19, 0x46, 0xeb,
	0x8e, 0xb0, 0x86, 0x25, 0x86, 0x42, 0x8b, 0x2b, 0x99, 0x44, 0x1b, 0x9e, 0xf0, 0xb6, 0x89, 0xd1,
	0x38, 0x46, 0xa5, 0xce, 0x59, 0xb4, 0xe9, 0x62, 0xa5, 0xed, 0x74, 0xa1, 0x50, 0x1f, 0x0b, 0x86,
	0xd1, 0x56, 0xa9, 0x0b, 0xef, 0x70, 0xba, 0x50, 0xa8, 0x4f, 0xdf, 0xe6, 0x5c, 0x22, 0x7b, 0xcd,
	0x53, 0x8c, 0x5a, 0xf6, 0x48, 0xe7, 0xfc, 0x26, 0x97, 0xb3, 0x57, 0xd7, 0xd7, 0x3c, 0xc6, 0x1e,
	0x0e, 0xb8, 0xc8, 0x68, 0x12, 0xdd, 0xb5, 0xea, 0x9c, 0xf3, 0x93, 0x07, 0xb0, 0x99, 0xa3, 0x54,
	0xe6, 0xff, 0xc7, 0x22, 0xed, 0xa3, 0x8c, 0x88, 0x9d, 0xfa, 0x86, 0x97, 0x74, 0x60, 0x9d, 0xab,
	0xcb, 0x22, 0x47, 0xe9, 0xe4, 0xd3, 0xde, 0x6d, 0xec, 0xad, 0xf6, 0x2a, 0x3e, 0x73, 0xde, 0x52,
	0x24, 0x18, 0x6d, 0xbb, 0xf3, 0x36, 0xff, 0xa6, 0x36, 0xe6, 0x7b, 0xce, 0xa2, 0x7b, 0xae, 0x3f,
	0x9c, 0xf5, 0xe8, 0x0f, 0x62, 0x6e, 0x0b, 0xff, 0x2e, 0x94, 0x82, 0x7e, 0x01, 0x5b, 0x67, 0x58,
	0xb9, 0x54, 0xc8, 0x8e, 0x17, 0xe8, 0x2d, 0xcf, 0xc2, 0xce, 0x27, 0xb7, 0xc6, 0x5c, 0x63, 0x76,
	0x3e, 0x22, 0x8f, 0xa1, 0x79, 0x86, 0x4e, 0xca, 0x8a, 0xb4, 0x7d, 0xee, 0xec, 0x05, 0xb2, 0xb3,
	0x5d, 0x75, 0x4e, 0xc8, 0x43, 0x58, 0x2d, 0xc9, 0x30, 0xf0, 0x09, 0xac, 0x1d, 0x5b, 0x11, 0xd7,
	0x63, 0xaf, 0xac, 0xc4, 0xeb, 0xb1, 0x27, 0x98, 0x60, 0x2d, 0xf6, 0x10, 0xe0, 0x0c, 0xf5, 0x65,
	0x91, 0xa6, 0x54, 0x8e, 0x09, 0xf1, 0x59, 0x5d, 0xaa, 0xb0, 0x24, 0xdb, 0x15, 0xdf, 0x04, 0xfc,
	0x0a, 0xd6, 0xcf, 0x50, 0x9b, 0x0b, 0xe2, 0x84, 0xf2, 0x24, 0x08, 0xfd, 0x06, 0x5a, 0x1e, 0x3d,
	0x7d, 0x8b, 0x71, 0xa1, 0xf9, 0x08, 0x43, 0xf0, 0x67, 0x40, 0x3c, 0xfe, 0x2a, 0x47, 0x49, 0xb5,
	0x93, 0x72, 0xf0, 0xd2, 0x5f, 0x8b, 0xfc, 0x68, 0x80, 0x99, 0x56, 0x21, 0xe8, 0x21, 0xc0, 0x77,
	0x3c, 0x63, 0xe1, 0xe0, 0x33, 0x20, 0x06, 0x74, 0xfd, 0xd7, 0x95, 0x34, 0x8b, 0x87, 0x18, 0x34,
	0xc0, 0x73, 0x68, 0x4f, 0x07, 0x28, 0x1b, 0x58, 0x85, 0x6f, 0xfb, 0x05, 0x57, 0xfa, 0x42, 0x8a,
	0x54, 0x84, 0xa0, 0x4f, 0x61, 0xd3, 0x1c, 0x39, 0x6a, 0xca, 0x93, 0x60, 0xf8, 0x71, 0xd9, 0x16,
	0x75, 0x48, 0xd7, 0x14, 0x75, 0x48, 0xd7, 0x12, 0xc1, 0xe4, 0xb7, 0x70, 0xf7, 0x44, 0xbc, 0xc9,
	0x12, 0x41, 0x59, 0x2d, 0x75, 0x3e, 0x87, 0x76, 0xc9, 0xff, 0x27, 0x79, 0x5e, 0xa9, 0xc9, 0xc5,
	0x1a, 0xdc, 0x1a, 0xb6, 0x4e, 0xb5, 0x06, 0xf8, 0x1a, 0xb6, 0x5c, 0xad, 0xea, 0xd2, 0xae, 0x5e,
	0x75, 0x69, 0x57, 0xb3, 0x5a, 0xf4, 0x21, 0xc0, 0xf1, 0x10, 0xe3, 0x5f, 0x4f, 0xed, 0xc3, 0x1d,
	0x56, 0x30, 0x0b, 0x5e, 0x54, 0x9f, 0xbc, 0x40, 0x81, 0x0f, 0x69, 0x36, 0xc0, 0x0b, 0xf3, 0xd2,
	0xd7, 0x93, 0x69, 0x0d, 0xd2, 0x37, 0xf3, 0x4b, 0xcc, 0x8a, 0x10, 0xf2, 0x09, 0x6c, 0x78, 0xd2,
	0xdd, 0x25, 0xf5, 0x66, 0xed, 0x99, 0xe7, 0x3d, 0xac, 0xad, 0x66, 0xc8, 0x4b, 0x4d, 0x35, 0x8f,
	0xc3, 0x57, 0xed, 0x94, 0x1d, 0x3a, 0xb7, 0x91, 0x86, 0x15, 0x75, 0x0d, 0xd0, 0xe9, 0xb9, 0x06,
	0xe8, 0xea, 0x1a, 0x0a, 0xba, 0x06, 0xfe, 0x9e, 0x2b, 0x2d, 0xe4, 0xf8, 0x28, 0xd6, 0x7c, 0xc4,
	0x75, 0xc8, 0xdb, 0xda, 0xfd, 0xe2, 0xe7, 0xfd, 0x01, 0xd7, 0xc3, 0xa2, 0xbf, 0x1f, 0x8b, 0xf4,
	0x80, 0xe1, 0x88, 0xa6, 0x7d, 0x9e, 0xf0, 0xec, 0xa0, 0x2f, 0xd8, 0x43, 0xff, 0xff, 0x30, 0x16,
	0x69, 0x2a, 0xb2, 0x03, 0x3b, 0x40, 0x7f, 0xc5, 0x7e, 0xbe, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x4c, 0x4c, 0x62, 0x37, 0xaf, 0x0f, 0x00, 0x00,
}
